fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .plugin(
                // 资料库命令放在应用内联插件里，权限由这里生成（capabilities 中的 `library:default`）。
                "library",
                tauri_build::InlinedPlugin::new()
                    .commands(&[
                        "current_library",
                        "create_library",
                        "browse",
                        "image",
                        "edit",
                        "sidebar",
                        "create_folder",
                        "rename_folder",
                        "move_folder",
                        "recovery",
                        "start_import",
                        "cancel_import",
                        "pick_folder",
                        "pick_files",
                        "image_tags",
                        "edit_tags",
                        "vocabulary",
                        "tag_groups",
                        "search_candidates",
                        "resolve_search",
                        "set_tag_approx",
                        "remove_tag_approx",
                        "personal_approx",
                        "image_rating",
                        "safe_mode",
                        "set_safe_mode",
                    ])
                    .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
            )
            .plugin(
                // 截图与钉图（#62）：主窗口、框选窗口与钉图窗口都用 `desktop:default`。
                "desktop",
                tauri_build::InlinedPlugin::new()
                    .commands(&[
                        "start_capture",
                        "frozen_screen",
                        "capture_ready",
                        "finish_capture",
                        "cancel_capture",
                        "pin_clipboard",
                        "pin_capture",
                        "pin_info",
                        "pin_ready",
                        "pin_menu",
                        "move_pin",
                        "zoom_pin",
                        "turn_pin",
                        "edge_hide",
                        "capture_history",
                        "collect_capture",
                        "delete_capture",
                    ])
                    .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
            ),
    )
    .expect("tauri-build 失败");
}
