// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 应用本身的名称与版本，供标题栏和“关于”显示。
 */
export type AppInfo = { productName: string, version: string, };
