// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShellSettingsView } from "./ShellSettingsView";

export type ApplicationSettingsRestored = { settings: ShellSettingsView, safeMode: boolean, problems: Array<string>, };
