// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkippedLibrary } from "./SkippedLibrary";

/**
 * 一次备份的结果。
 */
export type BackupReport = { snapshotId: string, 
/**
 * 快照完整：有问题时留在 `.incomplete`，不能用来恢复。
 */
complete: boolean, 
/**
 * 这次新复制的原文件。
 */
copied: number, copiedBytes: number, 
/**
 * 备份目标里已有、直接引用的原文件。
 */
reused: number, skipped: Array<SkippedLibrary>, problems: Array<string>, 
/**
 * 按保留策略删掉的旧快照。
 */
removedSnapshots: Array<string>, };
