// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupPlanView } from "./BackupPlanView";
import type { BackupProgress } from "./BackupProgress";
import type { BackupReport } from "./BackupReport";

/**
 * 应用壳推给界面的备份状态。
 */
export type BackupStatus = { plan: BackupPlanView, 
/**
 * 正在备份时的进度。
 */
running: BackupProgress | null, 
/**
 * 本次运行里最近一次备份的结果。
 */
lastReport: BackupReport | null, };
