// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupEstimate } from "./BackupEstimate";
import type { BackupScope } from "./BackupScope";

/**
 * 执行前给画师看的范围与容量。
 */
export type BackupPreview = { scope: BackupScope, estimate: BackupEstimate, 
/**
 * 备份目标现在在不在；不在时容量按全部需要复制估计。
 */
targetAvailable: boolean, };
