// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stamp } from "./Stamp";

/**
 * 最近一次失败。
 */
export type BackupFailure = { at: Stamp, reason: string, 
/**
 * 备份目标不在（移动盘没插等）。
 */
targetUnavailable: boolean, };
