// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupFailure } from "./BackupFailure";
import type { ScopeSelection } from "./ScopeSelection";
import type { Stamp } from "./Stamp";

/**
 * 给界面看的计划与状态。
 */
export type BackupPlanView = { target: string | null, selection: ScopeSelection, lastSuccess: Stamp | null, lastSnapshot: string | null, 
/**
 * 最近一次失败；之后成功过就清掉。
 */
lastFailure: BackupFailure | null, 
/**
 * 自动备份到期（下次退出或空闲时进行）。
 */
due: boolean, };
