// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkippedLibrary } from "./SkippedLibrary";

/**
 * 执行前的容量估计。
 */
export type BackupEstimate = { 
/**
 * 范围内的全部内容（数据库、原文件、参考组）。
 */
totalBytes: number, 
/**
 * 这次需要新写入备份目标的量（备份目标里已有的原文件不再复制）。
 */
newBytes: number, originals: number, newOriginals: number, 
/**
 * 现在读不到的资料库。
 */
unavailable: Array<SkippedLibrary>, };
