// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeItem } from "./ScopeItem";
import type { ScopeStep } from "./ScopeStep";
import type { Uncovered } from "./Uncovered";

/**
 * 算好的备份范围。资料库按登记顺序，参考组按名称。
 */
export type BackupScope = { libraries: Array<ScopeItem>, groups: Array<ScopeItem>, steps: Array<ScopeStep>, uncovered: Array<Uncovered>, };
