// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageCard } from "./ImageCard";

/**
 * 一页浏览结果。
 */
export type BrowsePage = { cards: Array<ImageCard>, 
/**
 * 还有下一页时给出游标。
 */
nextCursor: string | null, 
/**
 * 范围内的总张数。
 */
total: number, };
