// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseScope } from "./BrowseScope";

/**
 * 一次浏览请求。条件树与排序随查找切片加入。
 */
export type BrowseQuery = { scope: BrowseScope, 
/**
 * 上一页返回的 `nextCursor`；第一页为空。
 */
cursor: string | null, 
/**
 * 每页最多几张，上限 1000。
 */
limit: number, 
/**
 * 缩略图要显示的设备像素宽度；返回的地址按档位取整，不放大原图。
 */
thumbnailPx: number, };
