// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 浏览范围。
 */
export type BrowseScope = { "kind": "all" } | { "kind": "folder", id: string, } | { "kind": "folderTree", id: string, } | { "kind": "unassigned" } | { "kind": "trash" };
