// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagLabel } from "./TagLabel";

/**
 * 搜索框下拉中的一个候选标签。
 */
export type Candidate = { tag: TagLabel, 
/**
 * 经由别名或其他语言的名称命中时，是那个叫法；按显示名命中时为空。
 */
via: string | null, 
/**
 * 有这个标签的参考图张数。
 */
count: number, };
