// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 当前生产钉图渲染器选择的后备存储。float16 是可降级能力，不是浏览前提。
 */
export type CanvasBuffer = "float16" | "uint8" | "unavailable";
