// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Available` 表示完成了内置样本的相应操作，不表示图片色彩正确。
 */
export type CapabilityCheck = "available" | "missing" | "failed" | "timedOut";
