// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 保存参考组时对一张截图的决定。空资料库表示明确不把它加入参考组。
 */
export type CaptureChoice = { captureId: string, libraryId: string | null, };
