// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScreenRect } from "./ScreenRect";

/**
 * 查看器当前显示的参考图与客户区内的物理像素范围。F1 用它恢复来源与原图裁切。
 */
export type CaptureReference = { libraryId: string, imageId: string, shown: ScreenRect, visible: ScreenRect, };
