// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureReference } from "./CaptureReference";

/**
 * A current WebView frame, confirmed again after native screen capture.
 */
export type CaptureReferenceFrame = { generation: number, dpr: number, references: Array<CaptureReference>, };
