// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectedCapture } from "./CollectedCapture";

/**
 * 截图历史中的一张截图。
 */
export type CaptureEntry = { id: string, width: number, height: number, 
/**
 * 截取时间，Unix 毫秒。
 */
createdAt: number, 
/**
 * 还有钉图在显示它。钉住的截图不会因为太旧被丢弃。
 */
pinned: boolean, 
/**
 * 已收藏进哪些资料库。
 */
collected: Array<CollectedCapture>, };
