// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalizedName } from "./LocalizedName";
import type { TagAlias } from "./TagAlias";

export type CatalogNameEdit = { "kind": "prefer", name: LocalizedName, } | { "kind": "reset", lang: string, } | { "kind": "addAlias", alias: TagAlias, } | { "kind": "removeAlias", alias: TagAlias, };
