// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Safe configuration provenance; no original member IDs or labels leave the read adapter.
 */
export type CatalogGroupOrigin = { libraryId: string, libraryName: string, groupId: string, groupName: string, };
