// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApproxRelation } from "./ApproxRelation";

/**
 * Null explicit decisions remember deletion/ignore; automatic rows can be withdrawn by a conflict.
 */
export type CatalogApproxDecision = { a: string, b: string, relation: ApproxRelation | null, explicit: boolean, };
