// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonalApprox } from "./PersonalApprox";

export type CatalogApproxSource = { libraryId: string, libraryName: string, libraryRoot: string, rule: PersonalApprox, };
