// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalTagIdentity } from "./ExternalTagIdentity";
import type { LocalizedName } from "./LocalizedName";
import type { TagAlias } from "./TagAlias";
import type { TagNamespace } from "./TagNamespace";

/**
 * Initial definitions only. Name defaults, preferences and provenance migration are later actions.
 */
export type CatalogTag = { id: string, namespace: TagNamespace, names: Array<LocalizedName>, aliases: Array<TagAlias>, external: Array<ExternalTagIdentity>, };
