// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogGroupOrigin } from "./CatalogGroupOrigin";
import type { TagCount } from "./TagCount";
import type { TagNamespace } from "./TagNamespace";

export type CatalogGroupView = { id: string, name: string, namespace: TagNamespace | null, tags: Array<TagCount>, sources: Array<CatalogGroupOrigin>, };
