// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogGroupSource } from "./CatalogGroupSource";

/**
 * A null target records a migrated group which the user subsequently deleted.
 */
export type CatalogGroupMigration = { source: CatalogGroupSource, target: string | null, };
