// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApproxRelation } from "./ApproxRelation";
import type { PersonalApprox } from "./PersonalApprox";

export type CatalogApproxEdit = { "kind": "set", rules: Array<PersonalApprox>, } | { "kind": "remove", a: string, b: string, } | { "kind": "resolveConflict", a: string, b: string, revision: number, relation: ApproxRelation | null, };
