// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogApproxConflict } from "./CatalogApproxConflict";
import type { CatalogApproxEntry } from "./CatalogApproxEntry";

export type CatalogApproxView = { revision: number, entries: Array<CatalogApproxEntry>, conflicts: Array<CatalogApproxConflict>, };
