// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApproxRelation } from "./ApproxRelation";
import type { CatalogApproxOrigin } from "./CatalogApproxOrigin";
import type { TagLabel } from "./TagLabel";

export type CatalogApproxEntry = { a: TagLabel, b: TagLabel, relation: ApproxRelation, sources: Array<CatalogApproxOrigin>, };
