// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagGroupDefinition } from "./TagGroupDefinition";

export type CatalogGroupSource = { libraryId: string, libraryName: string, group: TagGroupDefinition, };
