// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CatalogGroupEdit = { "kind": "rename", groupId: string, name: string, } | { "kind": "delete", groupId: string, } | { "kind": "addMembers", groupId: string, tagIds: Array<string>, } | { "kind": "removeMembers", groupId: string, tagIds: Array<string>, } | { "kind": "orderMembers", groupId: string, tagIds: Array<string>, } | { "kind": "orderGroups", groupIds: Array<string>, };
