// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogApproxSource } from "./CatalogApproxSource";

export type CatalogApproxMigration = { source: CatalogApproxSource, a: string, b: string, confirmed: boolean, };
