// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogTag } from "./CatalogTag";
import type { LibraryTagMapping } from "./LibraryTagMapping";

export type CatalogInspection = { revision: number, tags: Array<CatalogTag>, mappings: Array<LibraryTagMapping>, };
