// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogGroupSource } from "./CatalogGroupSource";
import type { TagNamespace } from "./TagNamespace";

export type CatalogGroupDefinition = { id: string, name: string, namespace: TagNamespace | null, members: Array<string>, sources: Array<CatalogGroupSource>, };
