// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApproxRelation } from "./ApproxRelation";

export type CatalogApproxOrigin = { libraryId: string, libraryName: string, libraryRoot: string, relation: ApproxRelation, };
