// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageTags } from "./ImageTags";
import type { ResolvedTagIdentity } from "./ResolvedTagIdentity";

export type CatalogImageTags = { image: ImageTags, identities: Array<ResolvedTagIdentity>, };
