// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 往返检查的一项。
 */
export type CheckPart = { checked: number, problems: Array<string>, };
