// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ITU-T H.273 编码无关码点。
 */
export type Cicp = { primaries: number, transfer: number, matrix: number, fullRange: boolean, };
