// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 截图收藏进资料库后成为的参考图。
 */
export type CollectedCapture = { libraryId: string, imageId: string, };
