// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 色彩声明的来源，顺序与 Chromium 一致：PNG 为 cICP → iCCP → sRGB 块 → gAMA＋cHRM → 仅 gAMA。
 */
export type ColourDeclaration = "none" | "icc" | "cicp" | "srgb" | "gammaChromaticities" | "gamma";
