// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cicp } from "./Cicp";
import type { ColourDeclaration } from "./ColourDeclaration";
import type { ColourModel } from "./ColourModel";
import type { HdrKind } from "./HdrKind";
import type { IccSummary } from "./IccSummary";

/**
 * 一张原图的色彩描述（ADR-0005）。字段按文件内容识别，不看扩展名。
 */
export type ColourDescription = { 
/**
 * 文件格式：`jpeg`、`png`、`webp` 或 `gif`。
 */
format: string, 
/**
 * 每个通道的位深（PNG 可为 1、2、4、8、16）。
 */
bitDepth: number, colourModel: ColourModel, 
/**
 * 按 Chromium 的优先级实际生效的色彩声明。文件里带了但被忽略的 ICC 仍记在 `icc`。
 */
declaration: ColourDeclaration, 
/**
 * 文件里嵌入的 ICC 配置文件。
 */
icc: IccSummary | null, 
/**
 * PNG cICP 块（或 ICC 中的 cicp 标签）。
 */
cicp: Cicp | null, alpha: boolean, 
/**
 * EXIF 方向 1～8。
 */
orientation: number, 
/**
 * HDR 标记。带标记的原图首版只显示 `sdr` 派生图。
 */
hdr: HdrKind | null, 
/**
 * 是否带 HDR 母版显示器或亮度信息（PNG mDCV／cLLI）。
 */
hdrMetadata: boolean, 
/**
 * 是否动图（GIF、动态 WebP、APNG）。首版只显示首帧。
 */
animated: boolean, };
