// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TermInput } from "./TermInput";

/**
 * 搜索框里的一个条件：各项任一满足；`negate` 时排除满足的图。
 */
export type ConditionInput = { any: Array<TermInput>, negate: boolean, };
