// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Term } from "./Term";

/**
 * 条件树中的一个条件：各项任一满足；`negate` 时排除。`any` 为空的条件谁都不满足
 * （例如点选的标签已被删除）。
 */
export type Condition = { any: Array<Term>, negate: boolean, };
