// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";

/**
 * 可见的条件树：各条件同时满足。没有条件时是全部参考图。
 */
export type ConditionTree = { conditions: Array<Condition>, };
