// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 内容分级，从宽到严排列。
 */
export type ContentRating = "general" | "sensitive" | "questionable" | "explicit";
