// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 原图在 1:1 与放大时怎样显示（ADR-0005）。由导入时记录的色彩描述决定
 * （[`crate::fidelity::ColourDescription::needs_sdr_derivative`]）。
 */
export type DisplayRoute = "original" | "sdrDerivative";
