// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EagleTagMatch } from "./EagleTagMatch";
import type { UnmatchedEagleTag } from "./UnmatchedEagleTag";

/**
 * 迁入向导“标签的外部对应”一步的内容。
 */
export type EagleTagMapping = { matched: Array<EagleTagMatch>, 
/**
 * 按张数从多到少。
 */
unmatched: Array<UnmatchedEagleTag>, 
/**
 * 外部词表的名称个数，供界面说明匹配用的词表规模。
 */
vocabularySize: number, };
