// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 新位置疑似已登记的 Eagle 来源搬了家：已绑定条目至少一半出现在新位置。只是提议。
 */
export type EagleRelocation = { 
/**
 * 疑似搬家的已登记来源。
 */
sourceId: string, 
/**
 * 登记的位置。
 */
from: string, 
/**
 * 这次导入的新位置。
 */
to: string, 
/**
 * 已绑定条目出现在新位置的比例（百分比，向下取整）。
 */
overlapPercent: number, };
