// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EagleDiscoveryMethod } from "./EagleDiscoveryMethod";

export type EagleLibraryCandidate = { path: string, name: string, items: number, version: string | null, foundBy: EagleDiscoveryMethod, };
