// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eagle 曾永久删除的同一内容在本次任务中的处理方式，不改写长期删除记忆。
 */
export type EagleDeletedContentChoice = "skipDeleted" | "allowThisImport";
