// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 画师对疑似搬家位置的确认。
 */
export type EagleLocationChoice = { "kind": "moved", sourceId: string, } | { "kind": "separate" };
