// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchBasis } from "./MatchBasis";
import type { TagLabel } from "./TagLabel";

/**
 * 已有外部对应的 Eagle 标签。
 */
export type EagleTagMatch = { tag: TagLabel, count: number, external: Array<string>, basis: MatchBasis, };
