// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * External vocabulary + value. Neither is a display name or the stable identity.
 */
export type ExternalTagIdentity = { vocabulary: string, name: string, };
