// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 侧栏文件夹树的一个节点。
 */
export type FolderNode = { id: string, name: string, 
/**
 * 直接放在这个文件夹里、可见的参考图张数（不含子文件夹，不含回收站）。
 */
count: number, children: Array<FolderNode>, };
