// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 框选窗口要显示的冻结屏幕：整台显示器的物理像素尺寸，以及取图用的一次性标记。
 */
export type FrozenScreen = { width: number, height: number, 
/**
 * 冻结屏幕的地址：`screen/<标记>`，由应用壳映射到自定义协议 `capture`。
 */
image: string, };
