// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateItem } from "./GateItem";

/**
 * 交给门槛实验页面的计划：已入库的样本与本机环境。
 */
export type GatePlan = { items: Array<GateItem>, 
/**
 * 应用壳读到的本机环境（WebView2 版本、Windows、GPU 与驱动、显示器 ICC 关联）。
 */
environment: Record<string, unknown>, 
/**
 * 样本资料库的位置。
 */
library: string, 
/**
 * 无人值守运行（CI）：页面跑完自动保存，不等人填写。
 */
autoSave: boolean, };
