// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Patch } from "./Patch";

/**
 * 一个门槛样本。
 */
export type GateSample = { 
/**
 * 文件名，同时说明样本内容，例如 `p3-v4.jpg`。
 */
fileName: string, 
/**
 * 门槛分组，对应核查“尚未验证”一节的实验编号。
 */
group: string, 
/**
 * 中文说明。
 */
note: string, 
/**
 * 是否计入 ΔE2000 门槛。HDR 色调映射、细线等只记录结果、由画师目视。
 */
gated: boolean, patches: Array<Patch>, };
