// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Placement } from "./Placement";
import type { Region } from "./Region";

/**
 * 参考组成员：参考视图在这个参考组里的一次使用。
 */
export type GroupMember = { 
/**
 * 在参考组内唯一。
 */
id: string, libraryId: string, imageId: string, 
/**
 * 原图尺寸：局部总能核对是否在图内，资料库不在时也能按原尺寸保留布局。
 */
sourceWidth: number, sourceHeight: number, 
/**
 * 只显示原图的这一块（原图像素）；`None` 为整图。
 */
crop: Region | null, 
/**
 * 位置、缩放、翻转与旋转；尺寸由局部与缩放得出。
 */
placement: Placement, };
