// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 永久删除预览（#67）：某个参考组用到了将删除的哪些图。
 */
export type GroupUsage = { groupId: string, name: string, 
/**
 * 被用到的参考图（去重、按成员先后）。
 */
imageIds: Array<string>, };
