// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 参考组列表里的一项。读不懂的文件也列出来并说明原因，不悄悄消失。
 */
export type GroupSummary = { id: string, name: string, memberCount: number, 
/**
 * 引用到的资料库。
 */
libraryIds: Array<string>, updatedAt: number, 
/**
 * 这个文件读不懂时的原因；能打开时为 `None`。
 */
problem: string | null, };
