// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 钉图来自参考组的哪个成员（#66）。
 */
export type GroupMemberRef = { groupId: string, memberId: string, };
