// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ICC 配置文件的类型。LUT 型与 CMYK 不能由矩阵精确表示，转换误差须单独验收。
 */
export type IccKind = "matrix" | "lut" | "gray" | "invalid";
