// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IccKind } from "./IccKind";

export type IccSummary = { 
/**
 * 配置文件字节的 SHA-256。
 */
sha256: string, 
/**
 * 头部的版本号，例如 `4.3`、`2.1`。
 */
version: string, kind: IccKind, };
