// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentRating } from "./ContentRating";
import type { SnapshotTag } from "./SnapshotTag";

/**
 * 参考组包里一张参考图在导出时的整理信息快照。
 */
export type ImageSnapshot = { 
/**
 * 原文件的 SHA-256（小写十六进制）。导入时逐字节核对。
 */
sha256: string, originalName: string, width: number, height: number, 
/**
 * 收集时间（Unix 毫秒）。
 */
collectedAt: number, 
/**
 * 有效标签。
 */
tags: Array<SnapshotTag>, 
/**
 * 画师当时看到的备注（本库备注，没写时是来源备注）；没有备注时为空。
 */
note: string | null, sourceLinks: Array<string>, 
/**
 * 有效内容分级；带着它，导入后被封印的图在安全模式下立即遮蔽，不等重新打标。
 */
rating: ContentRating | null, };
