// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageTag } from "./ImageTag";
import type { TagLabel } from "./TagLabel";

/**
 * 一张参考图的标签：有效标签及其出处，以及被否决的标签。
 */
export type ImageTags = { imageId: string, tags: Array<ImageTag>, rejected: Array<TagLabel>, };
