// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 同一 Eagle 条目内容变化后留下的新旧版本（只列浏览视角下看得见的）。
 */
export type ImageVersions = { 
/**
 * 这张图取代的旧版本。
 */
previous: string | null, 
/**
 * 取代这张图的新版本，按进库先后。
 */
newer: Array<string>, };
