// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagLabel } from "./TagLabel";
import type { TagOrigin } from "./TagOrigin";

export type ImageTag = { tag: TagLabel, origins: Array<TagOrigin>, };
