// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 图片墙上的一张卡片。尺寸取自资料库记录（已按 EXIF 方向转正），界面据此布局。
 */
export type ImageCard = { id: string, width: number, height: number, 
/**
 * 缩略图地址：`<资料库 id>/<参考图 id>/<像素档位>`，由应用壳映射到自定义协议。
 */
thumbnail: string, };
