// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentRating } from "./ContentRating";

/**
 * 一张参考图的内容分级。
 */
export type ImageRating = { imageId: string, 
/**
 * 自动分级：各来源建议中最严格的一档；还没有建议时为空。
 */
suggested: ContentRating | null, 
/**
 * 有效分级（人工分级优先，#53）。
 */
effective: ContentRating | null, };
