// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderRef } from "./FolderRef";
import type { ImageNote } from "./ImageNote";
import type { ImageRating } from "./ImageRating";

/**
 * 查看单张参考图所需的详情。
 */
export type ImageDetail = { id: string, originalName: string, 
/**
 * 收集时间（Unix 毫秒）：Eagle btime → modificationTime → 导入时间。
 */
collectedAt: number, sourceLinks: Array<string>, width: number, height: number, 
/**
 * 所在的文件夹，按名称排序。
 */
folders: Array<FolderRef>, note: ImageNote, 
/**
 * 移进回收站的时间（Unix 毫秒）；不在回收站时为空。
 */
deletedAt: number | null, 
/**
 * 内容分级：自动、人工与有效。
 */
rating: ImageRating, };
