// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceNote } from "./SourceNote";

/**
 * 备注：画师写的与来源提供的分开保存。画师写过时显示画师的，否则显示来源的。
 */
export type ImageNote = { 
/**
 * 画师写的备注；`None` 表示没有写过（或已退回来源）。
 */
manual: string | null, 
/**
 * 各来源提供的备注（例如 Eagle 的整图备注）。普通文件导入没有。
 */
sources: Array<SourceNote>, };
