// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportOutcome } from "./ImportOutcome";

export type ImportItem = { path: string, outcome: ImportOutcome, };
