// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EagleDeletedContentChoice } from "./EagleDeletedContentChoice";

/**
 * 单次导入的选择；原有 [`super::Library::import`] 继续使用默认值。
 */
export type ImportOptions = { eagleDeletedContent: EagleDeletedContentChoice, };
