// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportProgress } from "./ImportProgress";
import type { ImportReport } from "./ImportReport";
import type { SaveDestination } from "./SaveDestination";

/**
 * A real task receipt bound to its chosen destination, not to current browsing.
 */
export type ImportTaskSnapshot = { taskId: string, destination: SaveDestination, libraryName: string, folderName: string, progress: ImportProgress, report: ImportReport | null, finishing: boolean, warnings: Array<string>, };
