// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportItem } from "./ImportItem";

/**
 * 导入任务的逐项结果。取消时只列出取消前处理过的项。
 */
export type ImportReport = { items: Array<ImportItem>, cancelled: boolean, };
