// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 导入进度：已处理几项、共几项。
 */
export type ImportProgress = { done: number, total: number, };
