// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EagleRelocation } from "./EagleRelocation";
import type { ImportItem } from "./ImportItem";

/**
 * 导入任务的逐项结果。取消时只列出取消前处理过的项。
 */
export type ImportReport = { 
/**
 * A boolean prompt only. The ordinary receipt never exposes the sealed subset size.
 */
sealedDuplicates: boolean, 
/**
 * Success details are intentionally coarsened together so subtraction cannot reveal a subset.
 */
privateSummary: boolean, trashDuplicates: boolean, items: Array<ImportItem>, cancelled: boolean, 
/**
 * 导入器识别到了 Eagle 来源，与画师使用的入口无关。
 */
fromEagle: boolean, 
/**
 * 这次迁入的 Eagle 资料库里已经不存在、但本库保留了副本的条目数。
 */
eagleMissing: number, 
/**
 * 像是已登记 Eagle 来源搬了家的新位置。画师确认前不迁入这些位置的任何条目，
 * 确认见 [`super::Library::confirm_eagle_location`]。
 */
eagleRelocations: Array<EagleRelocation>, };
