// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一项导入的结果。
 */
export type ImportOutcome = { "kind": "imported", imageId: string, } | { "kind": "merged", imageId: string, } | { "kind": "refreshed", imageId: string, } | { "kind": "newVersion", imageId: string, previousImageId: string, } | { "kind": "unsupported" } | { "kind": "readFailed", reason: string, };
