// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyNameResolution } from "./LegacyNameResolution";

export type LegacyNameDecision = { catalogId: string, lang: string, resolution: LegacyNameResolution, };
