// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyNameMigration } from "./LegacyNameMigration";
import type { LibraryRegistration } from "./LibraryRegistration";

export type LegacyNameMigrationWorkspace = { plan: LegacyNameMigration, libraries: Array<LibraryRegistration>, };
