// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LegacyNameSource = { libraryId: string, localTagId: string, legacyName: string, currentName: string, };
