// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyNameOutcome } from "./LegacyNameOutcome";

export type LegacyNameMigrationPreview = { revision: number, outcomes: Array<LegacyNameOutcome>, };
