// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyNameSource } from "./LegacyNameSource";
import type { TagNamespace } from "./TagNamespace";

export type LegacyNameGroup = { catalogId: string, namespace: TagNamespace, lang: string, defaultName: string | null, existingPreference: string | null, sources: Array<LegacyNameSource>, 
/**
 * Every attached provider affected by the shared choice, including unavailable providers.
 */
affectedLibraries: Array<string>, };
