// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyNameGroup } from "./LegacyNameGroup";

export type LegacyNameMigration = { revision: number, groups: Array<LegacyNameGroup>, };
