// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LegacyNameResolution = { "kind": "followDefault" } | { "kind": "keepLegacy", libraryId: string, localTagId: string, } | { "kind": "keepPreference" };
