// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 资料库身份与位置。
 */
export type LibraryInfo = { id: string, name: string, root: string, };
