// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaggingStatus } from "./TaggingStatus";

/**
 * 状态与所属资料库一起传给界面，迟到推送不能覆盖另一个库的状态。
 */
export type LibraryTaggingStatus = { libraryId: string, status: TaggingStatus, };
