// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegisteredLibrary } from "./RegisteredLibrary";

/**
 * 已登记资料库及本次检查的不可用原因；不可用的登记仍保留，移动盘接回后可重试。
 */
export type LibraryRegistration = { library: RegisteredLibrary, unavailable: string | null, };
