// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportProgress } from "./ImportProgress";
import type { ImportReport } from "./ImportReport";

/**
 * 资料库推送给界面的事件。
 */
export type LibraryEvent = { "kind": "listStale", libraryId: string, } | { "kind": "imagesChanged", libraryId: string, imageIds: Array<string>, } | { "kind": "vocabularyChanged", libraryId: string, revision: number, } | { "kind": "safeModeChanged", libraryId: string, on: boolean, } | { "kind": "taskProgress", libraryId: string, taskId: string, progress: ImportProgress, } | { "kind": "taskFinished", libraryId: string, taskId: string, report: ImportReport, };
