// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogMatchBasis } from "./CatalogMatchBasis";
import type { TagNameProvenance } from "./TagNameProvenance";
import type { VocabularyTag } from "./VocabularyTag";

export type LibraryTagMapping = { libraryId: string, localTagId: string, catalogId: string, 
/**
 * First attached definition. It must not become a global name preference implicitly.
 */
legacy: VocabularyTag, nameProvenance: TagNameProvenance, basis: CatalogMatchBasis, };
