// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 画师补上的外部对应。
 */
export type MappedExternal = { 
/**
 * 实际写入的外部名称（规范化后在词表中找到时用词表的写法）。
 */
external: string, 
/**
 * 在外部词表中。不在词表中的名称也会写入，但内置近似对应表多半不认识它。
 */
known: boolean, };
