// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnavailableReason } from "./UnavailableReason";

/**
 * 成员此刻的状态。
 */
export type MemberState = { "kind": "available", sealed: boolean, } | { "kind": "unavailable", reason: UnavailableReason, message: string, };
