// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberState } from "./MemberState";

/**
 * 一个成员的核对结果。
 */
export type MemberStatus = { memberId: string, libraryId: string, imageId: string, state: MemberState, };
