// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";

/**
 * 设置界面里的一个可选模型：名称、设备档位、显存或内存需求、大小、本机是否已装好。
 */
export type ModelOption = { key: string, label: string, device: Device, 
/**
 * DirectML 下的显存峰值估计。
 */
vramNeed: number, 
/**
 * CPU 下的内存峰值估计；0 表示不检查。
 */
ramNeed: number, 
/**
 * 首次使用要下载的字节数。
 */
size: number, 
/**
 * 已下载、校验（并改写）好，不必再下载。
 */
installed: boolean, };
