// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelOption } from "./ModelOption";

/**
 * 设置中“自动标签模型”一节：画师选的模型与可选的模型。
 */
export type ModelChoice = { 
/**
 * 画师选的模型 key；`None` 表示按本机条件自动选择。
 */
selected: string | null, options: Array<ModelOption>, };
