// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 参考组来自哪个参考组包（`imported_from_package`）。
 */
export type PackageProvenance = { packageId: string, 
/**
 * 导出这个包的参考组。
 */
groupId: string, 
/**
 * 导出时间（Unix 毫秒）。
 */
exportedAt: number, };
