// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageImage } from "./PackageImage";
import type { ReferenceGroup } from "./ReferenceGroup";

/**
 * 参考组包的清单。
 */
export type PackageManifest = { packageId: string, exportedAt: number, 
/**
 * 导出时的参考组，成员按来源库引用。
 */
group: ReferenceGroup, 
/**
 * 成员用到的参考图，每个“资料库＋参考图”一项。
 */
images: Array<PackageImage>, };
