// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageSnapshot } from "./ImageSnapshot";

/**
 * 包里的一张参考图：来源库中的身份、包内原文件与导出时的整理信息快照。
 */
export type PackageImage = { libraryId: string, imageId: string, 
/**
 * 包内原文件的位置（`originals/<sha256>.<ext>`）。
 */
file: string, size: number, snapshot: ImageSnapshot, };
