// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 样本上的一个纯色色块。
 */
export type Patch = { x: number, y: number, width: number, height: number, 
/**
 * 按样本色彩声明算出的 CIE Lab（D50）。
 */
lab: [number, number, number], 
/**
 * 不透明度 0～1。
 */
alpha: number, };
