// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupUsage } from "./GroupUsage";

/**
 * 永久删除预览：将删除的图、受影响的参考组和执行时要交回的令牌。
 */
export type PermanentDeletePreview = { 
/**
 * 将永久删除的参考图（去重，按给出的先后）。
 */
imageIds: Array<string>, 
/**
 * 用到这些图的参考组；为空时直接确认。
 */
groups: Array<GroupUsage>, 
/**
 * 执行永久删除时交回；回收站、受影响的参考组或安全模式变化后失效。
 */
token: string, };
