// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApproxRelation } from "./ApproxRelation";

/**
 * 个人近似对应表中的一条：两个库内标签（`tag_id`，无方向）与画师的判断。
 */
export type PersonalApprox = { a: string, b: string, relation: ApproxRelation, };
