// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApproxRelation } from "./ApproxRelation";

/**
 * 个人近似对应表中的一条：两个标签身份（无方向）与画师的判断。旧 Library 接口仍使用本地 ID；应用规则使用统一 ID。
 */
export type PersonalApprox = { a: string, b: string, relation: ApproxRelation, };
