// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApproxRelation } from "./ApproxRelation";
import type { TagLabel } from "./TagLabel";

/**
 * 资料库设置中列出的一条个人近似对应表条目。
 */
export type PersonalApproxEntry = { a: TagLabel, b: TagLabel, relation: ApproxRelation, };
