// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 钉图显示的是什么。#65 加入资料库中的参考视图。
 */
export type PinContent = { "kind": "capture", captureId: string, };
