// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 钉图显示的是什么。
 */
export type PinContent = { "kind": "capture", captureId: string, } | { "kind": "reference", libraryId: string, imageId: string, sourceWidth: number, sourceHeight: number, };
