// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinMotion } from "./PinMotion";
import type { SavedPin } from "./SavedPin";
import type { ScreenRect } from "./ScreenRect";

/**
 * 应用壳发给钉图窗口的一帧：画什么、原生窗口此刻在哪、内容要到哪（#64）。
 *
 * 内容在窗口里变换，不逐帧改原生窗口；`window` 与 `content` 不同时（动画中、收起时），
 * 页面把内容画在 `content` 相对 `window` 的位置。
 */
export type PinFrame = { pin: SavedPin, window: ScreenRect, content: ScreenRect, motion: PinMotion, 
/**
 * 原位遮蔽（模糊并显示小圆锁）：安全模式开启时被封印的参考图，或资料库没打开、核对不了的
 * 参考图（#60、#65）。画师确认显示这一张后为 false；截图钉图总是 false。
 */
veiled: boolean, 
/**
 * 动画结束后页面带着它调用 `settle_pin`；不是最新一帧的就不再改窗口。
 */
generation: number, };
