// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 钉图窗口显示的内容。
 */
export type PinInfo = { captureId: string, 
/**
 * 图片像素尺寸。
 */
width: number, height: number, };
