// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 钉图在桌面上的摆放：位置、缩放、翻转与旋转。
 *
 * 与参考组的成员摆放同义（#66 把它存进参考组）；透明度、锁定只属于桌面，不在这里。
 */
export type Placement = { 
/**
 * 原位：窗口外框左上角，物理像素。贴边隐藏不改变它。
 */
x: number, y: number, 
/**
 * 图片像素 → 物理像素。1 表示未缩放，逐像素显示。
 */
scale: number, flipH: boolean, flipV: boolean, 
/**
 * 顺时针四分之一圈数，0～3。
 */
rotation: number, };
