// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortableTagDefinition } from "./PortableTagDefinition";

/**
 * A library's explicit local correspondence. Initial local definitions may still acquire an
 * external correspondence during first enrollment; published application choices are authoritative.
 */
export type PortableTagBinding = { localTagId: string, definition: PortableTagDefinition, authoritative: boolean, };
