// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalTagIdentity } from "./ExternalTagIdentity";
import type { LocalizedName } from "./LocalizedName";
import type { TagAlias } from "./TagAlias";
import type { TagNamespace } from "./TagNamespace";

/**
 * A shared identity's content definition. Resolved display preferences never belong here.
 */
export type PortableTagDefinition = { id: string, namespace: TagNamespace, defaultNames: Array<LocalizedName>, aliases: Array<TagAlias>, external: Array<ExternalTagIdentity>, };
