// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentRating } from "./ContentRating";

/**
 * 来源给出的一条分级建议。
 */
export type RatingFact = { rating: ContentRating, 
/**
 * 模型给出的分数。
 */
score: number | null, };
