// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 打开资料库时的对账结果。
 */
export type RecoveryReport = { 
/**
 * 上次中断、已撤回的导入项（原图所在位置），可以重新导入。
 */
interrupted: string[], 
/**
 * 原文件夹里没有参考图引用的文件（相对资料库根目录）。只报告，不删除。
 */
orphans: string[], 
/**
 * 清掉的未发布暂存文件个数。
 */
discardedStaging: number, };
