// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupMember } from "./GroupMember";

/**
 * 一个参考组。
 */
export type ReferenceGroup = { id: string, name: string, 
/**
 * 毫秒时间戳。
 */
createdAt: number, updatedAt: number, members: Array<GroupMember>, };
