// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupMember } from "./GroupMember";
import type { RestoredFrom } from "./RestoredFrom";

/**
 * 一个参考组。
 */
export type ReferenceGroup = { id: string, name: string, 
/**
 * 毫秒时间戳。
 */
createdAt: number, updatedAt: number, members: Array<GroupMember>, 
/**
 * 从备份恢复出来的副本记下原参考组与备份快照（#69）；不是恢复出来的为 `None`。
 */
restoredFrom?: RestoredFrom, };
