// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 参考视角下的一张参考图（参考组成员、桌面钉图用）。
 */
export type ReferenceImage = { id: string, width: number, height: number, 
/**
 * 需要遮蔽：安全模式开启且这张图被封印。原位模糊并显示小圆锁，不移走。
 */
sealed: boolean, };
