// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberStatus } from "./MemberStatus";
import type { ReferenceGroup } from "./ReferenceGroup";

/**
 * 参考组及其成员此刻的状态（主窗口的参考组面板用）。
 */
export type ReferenceGroupView = { group: ReferenceGroup, 
/**
 * 与 `group.members` 一一对应。
 */
members: Array<MemberStatus>, };
