// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupMember } from "./GroupMember";
import type { PackageProvenance } from "./PackageProvenance";

/**
 * 一个参考组。
 */
export type ReferenceGroup = { id: string, name: string, 
/**
 * 毫秒时间戳。
 */
createdAt: number, updatedAt: number, members: Array<GroupMember>, 
/**
 * 从参考组包导入时，来自哪个包（#68）。
 */
importedFromPackage?: PackageProvenance, };
