// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 登记在本设备上的一个资料库。
 */
export type RegisteredLibrary = { id: string, name: string, root: string, };
