// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 截图上的一块区域，单位是物理像素，相对截图左上角。
 */
export type Region = { x: number, y: number, width: number, height: number, };
