// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagLabel } from "./TagLabel";

export type ResolvedTagIdentity = { localTagId: string, catalogId: string, 
/**
 * The shared definition label, for inspection. The image keeps its legacy display label.
 */
tag: TagLabel, };
