// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestoredGroup } from "./RestoredGroup";
import type { RestoredLibrary } from "./RestoredLibrary";
import type { RoundTripCheck } from "./RoundTripCheck";

/**
 * 一次恢复的结果。
 */
export type RestoreReport = { snapshotId: string, libraries: Array<RestoredLibrary>, groups: Array<RestoredGroup>, check: RoundTripCheck, };
