// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 恢复出的参考组来自哪个参考组、哪个备份快照。
 */
export type RestoredFrom = { groupId: string, backupId: string, };
