// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 恢复出的参考组。
 */
export type RestoredGroup = { oldId: string, id: string, name: string, };
