// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryInfo } from "./LibraryInfo";

/**
 * 恢复出的资料库。
 */
export type RestoredLibrary = { oldId: string, library: LibraryInfo, };
