// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 这个资料库是从哪个备份恢复出来的。
 */
export type RestoreProvenance = { oldLibraryId: string, backupId: string, restoredAt: number, };
