// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckPart } from "./CheckPart";

/**
 * 恢复后的往返检查：原图哈希、整理信息、参考组。
 */
export type RoundTripCheck = { originals: CheckPart, curation: CheckPart, groups: CheckPart, };
