// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeAssessment } from "./RuntimeAssessment";

export type RuntimeStatus = { 
/**
 * 查询实际启动的 WebView2；失败时不猜版本。
 */
webview2: string | null, assessment: RuntimeAssessment, };
