// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeAssessment } from "./RuntimeAssessment";

/**
 * WebView2 可用版本查询与本窗口能力检查。版本查询不独立证明实际运行进程的版本。
 */
export type RuntimeStatus = { webview2: string | null, assessment: RuntimeAssessment, };
