// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasBuffer } from "./CanvasBuffer";
import type { CapabilityCheck } from "./CapabilityCheck";

export type RuntimeCapabilities = { imageDecode: CapabilityCheck, canvas2d: CapabilityCheck, canvasBuffer: CanvasBuffer, };
