// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveDestination = { libraryId: string, 
/**
 * None explicitly means this library's unassigned area.
 */
folderId: string | null, };
