// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinContent } from "./PinContent";
import type { Placement } from "./Placement";
import type { Region } from "./Region";

/**
 * 一个桌面钉图要恢复的全部状态。
 */
export type SavedPin = { id: string, content: PinContent, 
/**
 * 只显示图片的这一块（图片像素）；`None` 为整张。
 */
crop: Region | null, 
/**
 * 显示部分的像素尺寸（裁切后、未旋转）。
 */
width: number, height: number, placement: Placement, };
