// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupMemberRef } from "./GroupMemberRef";
import type { PinContent } from "./PinContent";
import type { Placement } from "./Placement";
import type { Region } from "./Region";

/**
 * 一个桌面钉图要恢复的全部状态。
 */
export type SavedPin = { id: string, content: PinContent, 
/**
 * 只显示图片的这一块（图片像素）；`None` 为整张。
 */
crop: Region | null, 
/**
 * 显示部分的像素尺寸（裁切后、未旋转）。
 */
width: number, height: number, placement: Placement, 
/**
 * 透明度，[`MIN_OPACITY`]～1。只属于桌面钉图（#64）。
 */
opacity: number, 
/**
 * 锁定后不响应拖动与缩放（#64）。
 */
locked: boolean, 
/**
 * 从参考组打开的钉图来自哪个成员（#66）；存回这个参考组时更新那个成员。
 */
member?: GroupMemberRef, };
