// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit library and folder for saving. No folder means the library's unassigned area.
 */
export type SaveDestination = { libraryId: string, folderId: string | null, };
