// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 画师选的备份范围。
 */
export type ScopeSelection = { "kind": "all" } | { "kind": "libraries", ids: Array<string>, includeLinked: boolean, };
