// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 范围是怎么算出来的，逐步说明。
 */
export type ScopeStep = { "kind": "linkedGroup", libraryId: string, groupId: string, } | { "kind": "addedLibrary", groupId: string, libraryId: string, };
