// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 屏幕上的矩形，物理像素。
 */
export type ScreenRect = { x: number, y: number, width: number, height: number, };
