// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionInput } from "./ConditionInput";

/**
 * 画师在搜索框里组织的全部条件，各条件同时满足。
 */
export type SearchInput = { conditions: Array<ConditionInput>, };
