// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionInput } from "./ConditionInput";

/**
 * 画师在搜索框里组织的全部条件，各条件同时满足。
 */
export type SearchInput = { conditions: Array<ConditionInput>, 
/**
 * 精确查找：不展开相近标签。默认展开（近似查找）。
 */
exact: boolean, };
