// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShortcutBinding } from "./ShortcutBinding";

/**
 * 设置界面里应用壳一节的内容。
 */
export type ShellSettingsView = { autostart: boolean, shortcuts: Array<ShortcutBinding>, };
