// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShortcutBinding } from "./ShortcutBinding";

/**
 * 设置界面里应用壳一节的内容。
 */
export type ShellSettingsView = { autostart: boolean, shortcuts: Array<ShortcutBinding>, 
/**
 * 查找条件里标出相近标签的来源（内置／个人）。
 */
showApproxSource: boolean, 
/**
 * 诊断开关“强制 sRGB”的保存值（下次启动生效）。
 */
forceSrgb: boolean, 
/**
 * 本次运行实际采用的“强制 sRGB”；与保存值不同时界面提示重启。
 */
forceSrgbInEffect: boolean, 
/**
 * 使用日志是否开启。
 */
usageLog: boolean, };
