// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 可以绑定全局快捷键的动作。默认键沿用 Snipaste 的习惯。
 */
export type ShortcutAction = "capture" | "pinClipboard" | "hideAllPins";
