// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShortcutAction } from "./ShortcutAction";

/**
 * 设置界面显示的一行：动作、绑定的键、以及没能注册的原因。
 */
export type ShortcutBinding = { action: ShortcutAction, 
/**
 * `None` 表示画师清除了这个动作的快捷键。
 */
accelerator: string | null, 
/**
 * 有值时这个键当前没有生效（界面显示“未注册”）。
 */
problem: string | null, };
