// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderNode } from "./FolderNode";

/**
 * 侧栏所需的一切。标签分组随标签切片加入。
 */
export type Sidebar = { 
/**
 * “全部”里的张数（不含回收站）。
 */
all: number, 
/**
 * 回收站里的张数。
 */
trash: number, folders: Array<FolderNode>, };
