// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApproxSource } from "./ApproxSource";
import type { TagLabel } from "./TagLabel";

/**
 * 近似查找展开出的一个相近标签。
 */
export type SimilarTag = { tag: TagLabel, 
/**
 * 来自哪份近似对应表；同时有两份来源时记个人。
 */
source: ApproxSource, 
/**
 * 这一项中与它相近的标签（`tag_id`）。“以后都不展开”把其中每一对记为“不相近”。
 */
of: Array<string>, };
