// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeItem } from "./ScopeItem";

/**
 * 这次没能备份的资料库（例如所在的移动盘没插）。
 */
export type SkippedLibrary = { library: ScopeItem, reason: string, };
