// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalizedName } from "./LocalizedName";
import type { PortableTagDefinition } from "./PortableTagDefinition";
import type { TagNamespace } from "./TagNamespace";

/**
 * 快照里的一个标签：命名空间、各语言名称与外部名称，导入时据此在目标资料库中找到或新建标签。
 */
export type SnapshotTag = { 
/**
 * Present in modern content packages. Legacy packages continue through their compatibility resolver.
 */
definition?: PortableTagDefinition, 
/**
 * Only a source correspondence, never the identity on the destination library.
 */
localTagId?: string, namespace: TagNamespace, names: Array<LocalizedName>, external: Array<string>, };
