// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeItem } from "./ScopeItem";
import type { SkippedLibrary } from "./SkippedLibrary";
import type { Stamp } from "./Stamp";

/**
 * 备份目标里的一个完整快照。
 */
export type SnapshotSummary = { id: string, createdAt: Stamp, libraries: Array<ScopeItem>, groups: Array<ScopeItem>, skipped: Array<SkippedLibrary>, };
