// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalizedName } from "./LocalizedName";
import type { PortableTagDefinition } from "./PortableTagDefinition";
import type { TagNamespace } from "./TagNamespace";

/**
 * 快照标签：新版按稳定定义对应，旧版保留名称与外部对应的兼容解释。默认名称不包含程序偏好。
 */
export type SnapshotTag = { 
/**
 * Present in modern content packages. Legacy packages continue through their compatibility resolver.
 */
definition?: PortableTagDefinition, 
/**
 * Only a source correspondence, never the identity on the destination library.
 */
localTagId?: string, namespace: TagNamespace, names: Array<LocalizedName>, external: Array<string>, };
