// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 某个来源提供的备注。
 */
export type SourceNote = { 
/**
 * 来源种类，例如 `file`、`eagle`。
 */
source: string, text: string, };
