// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Stamp = { unixMs: number, 
/**
 * 本地时间比 UTC 早多少分钟（东八区为 480）。
 */
offsetMinutes: number, };
