// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 标签别名。`lang` 为空表示不区分语言。
 */
export type TagAlias = { name: string, lang: string | null, };
