// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogInspection } from "./CatalogInspection";
import type { LibraryRegistration } from "./LibraryRegistration";

export type TagCatalogWorkspace = { catalog: CatalogInspection, libraries: Array<LibraryRegistration>, };
