// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagLabel } from "./TagLabel";

export type TagCount = { tag: TagLabel, count: number, };
