// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagRef } from "./TagRef";

/**
 * 对参考图的一项标签编辑。
 */
export type TagEdit = { "kind": "add", tag: TagRef, } | { "kind": "reject", tag: TagRef, } | { "kind": "clear", tag: TagRef, };
