// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagCount } from "./TagCount";
import type { TagNamespace } from "./TagNamespace";

/**
 * 侧栏上的一个标签分组。
 */
export type TagGroupView = { id: string, name: string, 
/**
 * 不为空时，分组是这个命名空间中的全部标签。
 */
namespace: TagNamespace | null, tags: Array<TagCount>, };
