// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagNamespace } from "./TagNamespace";

/**
 * Durable legacy configuration, without image labels or visible counts.
 */
export type TagGroupDefinition = { id: string, name: string, namespace: TagNamespace | null, 
/**
 * Local identities, in the artist's chosen order. Namespace groups are dynamic.
 */
members: Array<string>, };
