// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagNamespace } from "./TagNamespace";

/**
 * 按界面语言显示的标签。
 */
export type TagLabel = { id: string, namespace: TagNamespace, 
/**
 * 界面语言的名称；没有时用其他语言的名称；都没有时是外部名称（下划线换成空格）。
 */
name: string, 
/**
 * 只有外部名称、还没有任何语言的名称（界面显示“文A”）。
 */
untranslated: boolean, 
/**
 * 有外部对应，参与内置近似对应表。
 */
hasExternal: boolean, };
