// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 标签命名空间。名称相同、命名空间不同的是两个标签。
 */
export type TagNamespace = "general" | "artist" | "character" | "work";
