// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 有效标签的一个出处。
 */
export type TagOrigin = { "kind": "source", source: string, score: number | null, } | { "kind": "manual" } | { "kind": "conflict" };
