// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagNamespace } from "./TagNamespace";

/**
 * 指向一个标签的方式。按名称或外部名称指向时，资料库中没有就新建。
 */
export type TagRef = { "kind": "id", id: string, } | { "kind": "named", namespace: TagNamespace, name: string, lang: string, } | { "kind": "external", namespace: TagNamespace, name: string, };
