// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 搜索框里的一项：点选的标签，或直接输入的文字。
 */
export type TermInput = { "kind": "tag", id: string, } | { "kind": "text", text: string, };
