// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SimilarTag } from "./SimilarTag";
import type { TagLabel } from "./TagLabel";

/**
 * 条件树中的一项，带显示用的标签名，界面照此显示条件。
 */
export type Term = { "kind": "tag", tag: TagLabel, 
/**
 * 近似查找展开的相近标签，与 `tag` 一起作为任一；精确查找时为空。
 */
similar: Array<SimilarTag>, } | { "kind": "text", text: string, 
/**
 * 名称或别名含这段文字的标签，按命名空间与名称排序。
 */
tags: Array<TagLabel>, 
/**
 * 近似查找展开的这些标签的相近标签（不含 `tags` 中已有的）；精确查找时为空。
 */
similar: Array<SimilarTag>, };
