// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 搜索框里的一项：点选的标签，或直接输入的文字。
 */
export type TermInput = { "kind": "tag", id: string, 
/**
 * “只这次”不展开的相近标签（`tag_id`）。
 */
dismissed: Array<string>, } | { "kind": "text", text: string, 
/**
 * “只这次”不展开的相近标签（`tag_id`）。
 */
dismissed: Array<string>, };
