// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 钉图的翻转与旋转（中心不动）。快捷键 H/V/R/Shift+R 与右键菜单共用（#63、#64）。
 */
export type Turn = "flipHorizontal" | "flipVertical" | "rotateClockwise" | "rotateCounterClockwise";
