// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 成员暂时不能显示的原因。成员与布局都保留，原因标在成员上。
 */
export type UnavailableReason = { "kind": "libraryNotRegistered" } | { "kind": "libraryUnavailable", detail: string, } | { "kind": "imageMissing" } | { "kind": "originalMissing" };
