// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeItem } from "./ScopeItem";

/**
 * 这次备份没覆盖的内容。
 */
export type Uncovered = { "kind": "library", group: ScopeItem, libraryId: string, libraryName: string | null, } | { "kind": "unreadableGroup", group: ScopeItem, problem: string, };
