// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 下载更新的进度，经 `update-progress` 事件推送。
 */
export type UpdateProgress = { downloaded: number, total: number | null, };
