// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 检查更新的结果（#70）。更新来自 GitHub Releases，安装包的签名由 Tauri updater 校验。
 */
export type UpdateStatus = { "state": "disabled", message: string, } | { "state": "manual", message: string, } | { "state": "unchecked" } | { "state": "upToDate" } | { "state": "available", version: string, 
/**
 * 发布说明。
 */
notes: string | null, } | { "state": "failed", message: string, };
