// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalizedName } from "./LocalizedName";
import type { TagAlias } from "./TagAlias";
import type { TagNamespace } from "./TagNamespace";

/**
 * 词表中的一个标签。
 */
export type VocabularyTag = { id: string, namespace: TagNamespace, names: Array<LocalizedName>, aliases: Array<TagAlias>, external: Array<string>, 
/**
 * 有这个有效标签的参考图张数。
 */
count: number, };
