// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VocabularyTag } from "./VocabularyTag";

/**
 * 标签词表快照，供 Search 使用；按 `revision` 缓存。
 */
export type Vocabulary = { revision: number, tags: Array<VocabularyTag>, };
