// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionTree } from "./ConditionTree";
import type { WorkspaceScope } from "./WorkspaceScope";

export type WorkspaceQuery = { scope: WorkspaceScope, conditions: ConditionTree, cursor: string | null, limit: number, thumbnailPx: number, };
