// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceSourceTarget = { libraryId: string, imageId: string, contentId: string, };
