// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryRegistration } from "./LibraryRegistration";
import type { Sidebar } from "./Sidebar";

/**
 * One provider root. Missing providers keep their identity and reason, without stale folders/counts.
 * `descendants` counts live visible images per subtree, deduplicated across folder memberships.
 */
export type WorkspaceDirectory = { registration: LibraryRegistration, sidebar: Sidebar | null, unassigned: number, descendants: { [key in string]: number }, };
