// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSource } from "./WorkspaceSource";

export type WorkspaceCard = { 
/**
 * Stable byte identity, also used for scroll anchors.
 */
id: string, width: number, height: number, thumbnail: string, adult: boolean, 
/**
 * Explicit available matching source used for display; browsing never activates it.
 */
libraryId: string, imageId: string, sources: Array<WorkspaceSource>, };
