// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryRegistration } from "./LibraryRegistration";

export type WorkspaceStatus = { revision: string, libraries: Array<LibraryRegistration>, };
