// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceDirectory } from "./WorkspaceDirectory";
import type { WorkspaceStatus } from "./WorkspaceStatus";

export type WorkspaceDirectories = { status: WorkspaceStatus, providers: Array<WorkspaceDirectory>, };
