// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceCard } from "./WorkspaceCard";
import type { WorkspaceStatus } from "./WorkspaceStatus";

export type WorkspacePage = { cards: Array<WorkspaceCard>, nextCursor: string | null, total: number, status: WorkspaceStatus, };
