// #78 T17: production waterfall capture, current geometry, original pixels and native side effects.
// node e2e/wall-capture.mjs <frozen kinshoko.exe> <msedgedriver.exe> <build-source.json> [--race-only]
import { spawn, spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync, readFileSync, copyFileSync, existsSync, appendFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve, join } from "node:path";
import { deflateSync } from "node:zlib";
import { isDeepStrictEqual } from "node:util";
const [, , appArg, edgeArg, manifestArg] = process.argv;
if (!appArg || !edgeArg || !manifestArg) throw new Error("node e2e/wall-capture.mjs <kinshoko.exe> <msedgedriver.exe> <build-source.json> [--race-only]");
const raceOnly = process.argv.includes("--race-only");
const application = resolve(appArg), port = Number(process.env.KINSHOKO_WEBDRIVER_PORT ?? 4592);
const work = resolve("work/e2e", `wall-capture-${raceOnly ? "race-" : ""}${Date.now()}`);
for (const path of [work, join(work,"libraries"), join(work,"sources"), join(work,"app-data"), join(work,"webview")]) mkdirSync(path,{recursive:true});
const manifest = JSON.parse(readFileSync(manifestArg,"utf8").replace(/^\uFEFF/,""));
const sha = path => createHash("sha256").update(readFileSync(path)).digest("hex");
const result = { status:"running", source:manifest.source, tree:manifest.tree, binarySha256:sha(application), application, manifest:resolve(manifestArg), scriptSha256:sha(new URL(import.meta.url)), scriptSource:spawnSync("git",["rev-parse","HEAD"],{encoding:"utf8",windowsHide:true}).stdout.trim(), mode:raceOnly?"clipboard-revocation":"wall", nativeHelperSha256:sha(resolve("e2e/native-wall-observe.py")), pixelHelperSha256:sha(resolve("e2e/native-wall-pixels.py")), assertions:[], samples:[], work, startedAt:new Date().toISOString() };
if(result.binarySha256!==manifest.binarySha256.toLowerCase()) throw new Error("Binary differs from frozen source manifest");
for(const name of ["wall-capture.mjs","native-wall-observe.py","native-wall-pixels.py","native-clipboard-observe.py"])copyFileSync(resolve("e2e",name),join(work,name));
copyFileSync(resolve(manifestArg),join(work,"frozen-build-manifest.json"));
const settingsPath=join(process.env.APPDATA,"dev.kinshoko.spec78t17test","settings.json");
function recordSettings(phase){const exists=existsSync(settingsPath),entry={path:settingsPath,exists,observedAt:new Date().toISOString()};if(exists){const bytes=readFileSync(settingsPath);writeFileSync(join(work,`settings-${phase}.json`),bytes);entry.sha256=createHash("sha256").update(bytes).digest("hex");}return entry;}
result.settingsBefore=recordSettings("before");
const checksum = Array.from({length:256},(_,c)=>{for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
function chunk(type,data){const body=Buffer.concat([Buffer.from(type),data]);let crc=0xffffffff;for(const b of body)crc=checksum[(crc^b)&255]^(crc>>>8);const len=Buffer.alloc(4),tail=Buffer.alloc(4);len.writeUInt32BE(data.length);tail.writeUInt32BE((crc^0xffffffff)>>>0);return Buffer.concat([len,body,tail]);}
function png(path,width,height,seed=0){const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=6;const bytes=Buffer.alloc((width*4+1)*height);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const p=y*(width*4+1)+1+x*4;bytes[p]=(x+seed)%256;bytes[p+1]=y%256;bytes[p+2]=x%2*255;bytes[p+3]=255;}writeFileSync(path,Buffer.concat([Buffer.from("89504e470d0a1a0a","hex"),chunk("IHDR",header),chunk("IDAT",deflateSync(bytes)),chunk("IEND",Buffer.alloc(0))]));}
const detail=join(work,"sources",raceOnly?"slow-original.png":"original-detail.png");
const originalWidth=raceOnly?10000:4800,originalHeight=raceOnly?8000:3200;
png(detail,originalWidth,originalHeight);
const sourceHash=sha(detail);
const endpoint=`http://127.0.0.1:${port}`, ELEMENT="element-6066-11e4-a52e-4f735466cecf";
async function wd(method,path,body){const r=await fetch(endpoint+path,{method,headers:{"content-type":"application/json"},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(120000)});const v=await r.json();if(v.value?.error)(result.webdriverErrorValues??=[]).push({observedAt:new Date().toISOString(),method,path,httpStatus:r.status,httpOk:r.ok,value:v.value});if(!r.ok)throw new Error(`${method} ${path} HTTP ${r.status}: ${JSON.stringify(v.value)}`);return v.value;}
const delay=ms=>new Promise(done=>setTimeout(done,ms));
async function until(label,read,timeout=45000){const end=Date.now()+timeout;let last;while(Date.now()<end){try{const v=await read();if(v)return v;}catch(e){last=e;}await delay(100);}throw new Error(`Timed out ${label}${last?`: ${last.message}`:""}`);}
function check(value,label){if(!value)throw new Error(label);result.assertions.push(label);console.log(`PASS ${label}`);}
let base, driver, occluder;
const nativeLog={events:[],stdout:"",stderr:""};
function observeNativeLog(stream,bytes){
 appendFileSync(join(work,"native-driver-"+stream+".log"),bytes);
 process[stream].write(bytes);nativeLog[stream]+=bytes.toString("utf8");
 let end;
 while((end=nativeLog[stream].indexOf("\n"))>=0){
  const line=nativeLog[stream].slice(0,end).trim();nativeLog[stream]=nativeLog[stream].slice(end+1);
  if(line.startsWith("clipboard.")||line.startsWith("capture.source.prepare.")){const at=line.match(/ at=(\d+)/);nativeLog.events.push({receivedAt:Date.now(),at:at?Number(at[1]):null,line});}
 }
}
function clipboardMetadata(){const r=spawnSync(process.env.KINSHOKO_PYTHON??"python",["e2e/native-clipboard-observe.py"],{encoding:"utf8",windowsHide:true});if(r.status!==0)throw new Error(r.stderr);return JSON.parse(r.stdout);}
result.clipboardMetadataHelperSha256=sha("e2e/native-clipboard-observe.py");

const exec=(script,args=[])=>wd("POST",`${base}/execute/sync`,{script,args});
async function invoke(command,args={}){const v=await wd("POST",`${base}/execute/async`,{script:"const done=arguments[arguments.length-1]; window.__TAURI_INTERNALS__.invoke(arguments[0],arguments[1]).then(value=>done({value}),error=>done({failure:String(error)}));",args:[command,args]});if(v.failure)throw new Error(`${command}: ${v.failure}`);return v.value;}
const library=(name,args)=>invoke(`plugin:library|${name}`,args), desktop=(name,args)=>invoke(`plugin:desktop|${name}`,args);
const native=(name,label="main",args={})=>invoke(`plugin:window|${name}`,{label,...args});
const windows=()=>invoke("plugin:window|get_all_windows");
const click=async(xpath)=>wd("POST",`${base}/element/${(await wd("POST",`${base}/element`,{using:"xpath",value:xpath}))[ELEMENT]}/click`,{});
const screenshot=async(name)=>writeFileSync(join(work,name),Buffer.from(await wd("GET",`${base}/screenshot`),"base64"));
async function startSession(){const dpr=process.env.KINSHOKO_CAPTURE_DPR;const s=await wd("POST","/session",{capabilities:{alwaysMatch:{"tauri:options":{application,webviewOptions:{userDataFolder:join(work,"webview"),additionalBrowserArguments:dpr?[`force-device-scale-factor=${Number(dpr)}`]:[]}}}}});base=`/session/${s.sessionId}`;await wd("POST",`${base}/timeouts`,{script:120000});await until("IPC ready",()=>exec("return !!window.__TAURI_INTERNALS__?.invoke"));result.capabilities=s.capabilities;}
async function reload(){const marker=Date.now()+Math.random();await exec("window.__reloadMarker=arguments[0];location.reload()",[marker]);await until("new wall document",()=>exec("return window.__reloadMarker!==arguments[0]&&!!document.querySelector('.wall')",[marker]));if(await exec("return !!document.querySelector('.import-popup:not([hidden])')"))await click("//button[@aria-label='关闭导入操作']");await observeRequests();await observeLibraryEvents();}
async function observeRequests(){
 await exec(`if(!window.__wallTrace){window.__wallTrace=[];const sample=reason=>{const w=document.querySelector('.wall');if(!w)return;const b=w.getBoundingClientRect(),a=document.activeElement;const value={at:Date.now(),reason,scrollTop:w.scrollTop,scrollHeight:w.scrollHeight,width:w.clientWidth,height:w.clientHeight,total:w.dataset.total,wall:[b.x,b.y,b.width,b.height],document:window.__documentMarker,active:{tag:a?.tagName,cls:a?.className,id:a?.closest('.card')?.dataset.id},cards:[...w.querySelectorAll('.card')].map(n=>({id:n.dataset.id,top:n.getBoundingClientRect().top,loaded:!!n.querySelector('img')?.naturalWidth}))};window.__wallTrace.push(value);if(window.__wallTrace.length>300)window.__wallTrace.shift();};window.__sampleWall=sample;for(const n of ['scroll','resize','focus','blur'])window.addEventListener(n,()=>sample(n),true);let last='';new MutationObserver(()=>{const w=document.querySelector('.wall');const signature=w?[w.scrollTop,w.clientWidth,w.scrollHeight,w.dataset.total,...[...w.querySelectorAll('.card')].map(n=>n.dataset.id)].join('|'):'';if(signature!==last){last=signature;sample('DOM-layout-change');}}).observe(document.documentElement,{childList:true,subtree:true,attributes:true});sample('installed');}`);
 const descriptor=await exec("const d=Object.getOwnPropertyDescriptor(window.__TAURI_INTERNALS__,'invoke');return {writable:d?.writable,configurable:d?.configurable,hasSetter:!!d?.set}");
 result.invokeDescriptor=descriptor;
 await wd("POST",`${base}/execute/async`,{script:"const done=arguments[arguments.length-1];if(window.__captureRequests){done(true);return;}window.__captureRequests=[];window.__documentMarker=crypto.randomUUID();const handler=window.__TAURI_INTERNALS__.transformCallback(e=>{window.__captureRequests.push(e.payload.request);window.__sampleWall?.('capture-reference-request:'+e.payload.request);if(window.__lateReport){const late=window.__lateReport;window.__lateReport=null;window.__lateSent=late;setTimeout(()=>window.__TAURI_INTERNALS__.invoke('plugin:desktop|report_capture_references',late),5);}});window.__TAURI_INTERNALS__.invoke('plugin:event|listen',{event:'capture-reference-request',target:{kind:'Any'},handler}).then(()=>done(true),error=>done({failure:String(error)}));",args:[]});
 await wd("POST",`${base}/execute/async`,{script:"const done=arguments[arguments.length-1];if(window.__workspaceObserved){done(true);return;}window.__workspaceObserved=true;window.__workspaceEvents=[];const handler=window.__TAURI_INTERNALS__.transformCallback(e=>{window.__workspaceEvents.push({at:Date.now(),revision:e.payload.revision});window.__sampleWall?.('workspace-changed:'+e.payload.revision);});window.__TAURI_INTERNALS__.invoke('plugin:event|listen',{event:'workspace-changed',target:{kind:'Any'},handler}).then(()=>done(true),error=>done({failure:String(error)}));",args:[]});
}
async function observeLibraryEvents(){
 await wd("POST",base+"/execute/async",{script:"const done=arguments[arguments.length-1];if(window.__libraryObserved){done(true);return;}window.__libraryObserved=true;window.__libraryEvents=[];window.__safeSettingEvents=[];const listen=(event,read)=>{const handler=window.__TAURI_INTERNALS__.transformCallback(e=>read(e.payload));return window.__TAURI_INTERNALS__.invoke('plugin:event|listen',{event,target:{kind:'Any'},handler});};Promise.all([listen('library-event',payload=>{const {libraryId,kind,on,taskId}=payload;window.__libraryEvents.push({at:Date.now(),libraryId,kind,on,taskId});if(window.__libraryEvents.length>300)window.__libraryEvents.shift();window.__sampleWall?.('library-event:'+kind);}),listen('safe-mode-setting',on=>{window.__safeSettingEvents.push({at:Date.now(),on});if(window.__safeSettingEvents.length>100)window.__safeSettingEvents.shift();window.__sampleWall?.('safe-mode-setting:'+on);})]).then(()=>done(true),error=>done({failure:String(error)}));",args:[]});
}
async function staleInput(){const requests=await exec("return window.__captureRequests");check(requests.length>=2,"public production capture requests are observed without replacing immutable invoke");return {request:requests[0],frame:{instance:"stale-harness-input",generation:0,dpr:await exec("return devicePixelRatio"),references:[]}};}
async function importFiles(info,paths){const id=await library("start_import",{libraryId:info.id,source:{paths},destination:{libraryId:info.id,folderId:null}});return until("import complete",async()=>{const task=(await library("import_tasks")).find(t=>t.taskId===id);if(task?.report&&!task.finishing){check(task.report.items.every(i=>["imported","merged"].includes(i.outcome.kind)),"synthetic originals import through production task");return task.report;}return null;},120000);}
const browse=(id,safeMode=true)=>library("workspace_browse",{query:{scope:{kind:"library",libraryId:id,scope:{kind:"all"}},conditions:{conditions:[]},cursor:null,limit:500,thumbnailPx:256},safeMode});
async function shownCard(contentId){const box=await until("loaded visible waterfall image",()=>exec("const card=[...document.querySelectorAll('.card')].find(n=>n.dataset.id===arguments[0]);const i=card?.querySelector('img');if(!i?.complete||!i.naturalWidth||card.dataset.veiled==='true')return null;const b=i.getBoundingClientRect(),v=document.querySelector('.wall').getBoundingClientRect();if(b.bottom<=v.top||b.top>=v.bottom)return null;return {left:b.left,top:b.top,width:b.width,height:b.height,dpr:devicePixelRatio,thumbWidth:i.naturalWidth};",[contentId]));const scale=Math.min(box.width/originalWidth,box.height/originalHeight),dpr=box.dpr;const left=Math.round((box.left+(box.width-originalWidth*scale)/2)*dpr),top=Math.round((box.top+(box.height-originalHeight*scale)/2)*dpr);const right=Math.round((box.left+(box.width+originalWidth*scale)/2)*dpr),bottom=Math.round((box.top+(box.height+originalHeight*scale)/2)*dpr);const origin=await native("inner_position");return {...box,contentId,x:origin.x+left,y:origin.y+top,width:right-left,height:bottom-top};}
async function bottomOriginal(contentId){await until("original visible after real paginated wall scroll",async()=>{await exec("const w=document.querySelector('.wall');w.scrollTop=w.scrollHeight;w.dispatchEvent(new Event('scroll',{bubbles:true}));");return exec("const n=[...document.querySelectorAll('.card')].find(n=>n.dataset.id===arguments[0]),i=n?.querySelector('img'),w=document.querySelector('.wall');if(!i?.complete||!i.naturalWidth)return false;const b=i.getBoundingClientRect(),v=w.getBoundingClientRect();return b.bottom>v.top&&b.top<v.bottom",[contentId]);});return shownCard(contentId);}
async function begin(){await wallState("before-native-focus");const focus=observeNative("focus",occluder?{x:result.occluder.requested.x+10,y:result.occluder.requested.y+10}:undefined);(result.foregrounds??=[]).push(focus);await wallState("after-native-focus");if(occluder){const observed=focus.testOccluderWindows?.find(w=>w.hwnd===result.occluder.ready.hwnd&&w.visible&&!w.iconic);result.occluder.afterMainFocus=focus;check(observed&&focus.pointWindow?.rootHwnd===observed.hwnd&&focus.pointWindow?.rootPid===occluder.pid,"actual OS point hit still identifies the owned fixture after main foreground activation");}check(focus.foregroundPid===focus.pid&&focus.foregroundHwnd===focus.mainHwnd,"actual foreground HWND belongs to the exact frozen application");if(await exec("return !!document.querySelector('.import-popup:not([hidden])')"))await click("//button[@aria-label='关闭导入操作']");await wallState("before-start-capture");await desktop("start_capture");await wallState("after-start-capture-return");await until("frozen native window",()=>native("is_visible","capture"));const frozen=await desktop("frozen_screen");return {frozen,token:frozen.image.slice("screen/".length),origin:await native("inner_position","capture")};}
function selection(shown,capture){const offsetX=Math.max(4,Math.floor(shown.width/4)),offsetY=Math.max(4,Math.floor(shown.height/4)),width=Math.max(4,Math.floor(shown.width/8)),height=Math.max(4,Math.floor(shown.height/8));return {region:{x:shown.x+offsetX-capture.origin.x,y:shown.y+offsetY-capture.origin.y,width,height},crop:{x:Math.floor(offsetX*originalWidth/shown.width),y:Math.floor(offsetY*originalHeight/shown.height),width:Math.ceil((offsetX+width)*originalWidth/shown.width)-Math.floor(offsetX*originalWidth/shown.width),height:Math.ceil((offsetY+height)*originalHeight/shown.height)-Math.floor(offsetY*originalHeight/shown.height)}};}
async function wallState(stage){const state=await exec("window.__sampleWall?.(arguments[0]);return {wall:window.__wallTrace?.at(-1),trace:window.__wallTrace,requests:window.__captureRequests,workspaceEvents:window.__workspaceEvents,libraryEvents:window.__libraryEvents,safeSettingEvents:window.__safeSettingEvents,document:window.__documentMarker,label:window.__TAURI_INTERNALS__.metadata.currentWindow.label,dpr:devicePixelRatio,viewport:[innerWidth,innerHeight],anchors:Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('kinshoko.wall.')).map(k=>[k,localStorage.getItem(k)]))}",[stage]);const {trace,...current}=state;(result.wallTraces??={})[state.document??"unmarked"]=trace;(result.wallStages??=[]).push({stage,observedAt:new Date().toISOString(),...current});return current;}
function readClipboard(label){const r=spawnSync(process.env.KINSHOKO_PYTHON??"python",["e2e/native-wall-pixels.py","clipboard",join(work,`${label}.png`)],{encoding:"utf8",windowsHide:true});if(r.status!==0)throw new Error(r.stderr);return JSON.parse(r.stdout);}
async function frozenPatch(frozen,shown,selected){const main=await wd("GET",`${base}/window`);let bytes;try{for(const handle of await wd("GET",`${base}/window/handles`)){if(handle===main)continue;await wd("POST",`${base}/window`,{handle});if(await exec("return window.__TAURI_INTERNALS__.metadata.currentWindow.label==='capture'")){await until("painted frozen native screen",()=>exec("const i=document.querySelector('.capture-screen');return i?.complete&&i.naturalWidth>0"));const raster=await exec("const r=document.querySelector('.capture-screen').getBoundingClientRect();return {dpr:devicePixelRatio,viewport:[innerWidth,innerHeight],image:[r.x,r.y,r.width,r.height]}");(result.captureRasters??=[]).push(raster);check(Math.abs(raster.image[0])+Math.abs(raster.image[1])<.01&&Math.abs(raster.image[2]*raster.dpr-frozen.frozen.width)<.01&&Math.abs(raster.image[3]*raster.dpr-frozen.frozen.height)<.01,"frozen image paints at native physical dimensions with zero origin");bytes=Buffer.from(await wd("GET",`${base}/screenshot`),"base64");break;}}}finally{await wd("POST",`${base}/window`,{handle:main});}if(!bytes)throw new Error("Frozen native capture WebView was not observed");const shownRect=[shown.x-frozen.origin.x,shown.y-frozen.origin.y,shown.width,shown.height],region=[selected.region.x,selected.region.y,selected.region.width,selected.region.height];const r=spawnSync(process.env.KINSHOKO_PYTHON??"python",["e2e/native-wall-pixels.py","frozen",join(work,`frozen-${frozen.token}-source.png`),JSON.stringify(shownRect),JSON.stringify(region),JSON.stringify([frozen.frozen.width,frozen.frozen.height])],{input:bytes,encoding:"utf8",windowsHide:true});if(r.status!==0)throw new Error(r.stderr);return JSON.parse(r.stdout);}
async function capture(shown,action,expectedOriginal=true){const before=await windows(),frozen=await begin(),frozenShown=shown.contentId?await shownCard(shown.contentId):shown,selected=selection(frozenShown,frozen);(result.actions??=[]).push({action,measuredBefore:shown,frozenShown,token:frozen.token,...selected,nativeAfterOverlayShown:observeNative("observe",{x:frozenShown.x+Math.floor(frozenShown.width/4),y:frozenShown.y+Math.floor(frozenShown.height/4)}),mainFocused:await native("is_focused"),domAtSelection:await exec("const r=arguments[0],p=arguments[1];return document.elementsFromPoint((r.x-p.x)/devicePixelRatio,(r.y-p.y)/devicePixelRatio).slice(0,6).map(n=>({tag:n.tagName,cls:n.className,id:n.closest('.card')?.dataset.id}))",[{x:frozenShown.x+Math.floor(frozenShown.width/4),y:frozenShown.y+Math.floor(frozenShown.height/4)},await native("inner_position")])});const patch=await frozenPatch(frozen,frozenShown,selected);result.actions.at(-1).frozenPixels=patch;if(expectedOriginal)check(patch.sourcePattern.red>=8&&patch.sourcePattern.green>=5&&patch.selectedPattern.red>=1&&patch.selectedPattern.green>=1,"selected position is inside the original's distinct grid on the actual frozen screen");else check(patch.selectedUniformBlue===true,"actual frozen selection contains only the external fixture blue pixels");await desktop("finish_capture",{token:frozen.token,region:selected.region,action});let pin;if(action==="pin"){const label=await until("new native reference pin",async()=>(await windows()).find(w=>w.startsWith("pin-")&&!before.includes(w)));pin=await desktop("pin_frame",{pin:label.slice(4)});await until("native pin shown",()=>native("is_visible",label));}return {...selected,pin};}
async function clearPins(){const main=await wd("GET",`${base}/window`);for(const handle of await wd("GET",`${base}/window/handles`)){if(handle===main)continue;await wd("POST",`${base}/window`,{handle});const label=await exec("return window.__TAURI_INTERNALS__.metadata.currentWindow.label");if(label.startsWith("pin-"))await exec("void window.__TAURI_INTERNALS__.invoke('plugin:desktop|close_pin',{pin:arguments[0]});return true",[label.slice(4)]);await wd("POST",`${base}/window`,{handle:main});if(label.startsWith("pin-"))await until("own pin closed",async()=>!(await windows()).includes(label));}}
function clipboardFile(entry){const path=join(work,"app-data","captures",`${entry.id}.png`);copyFileSync(path,join(work,`clipboard-${entry.id}.png`));const r=spawnSync(process.env.KINSHOKO_PYTHON??"python",["-c","from PIL import Image; import json,sys; im=Image.open(sys.argv[1]).convert('RGBA'); print(json.dumps({'size':im.size,'corners':[im.getpixel((0,0)),im.getpixel((im.width-1,0)),im.getpixel((0,im.height-1)),im.getpixel((im.width-1,im.height-1))]}))",path],{encoding:"utf8",windowsHide:true});if(r.status!==0)throw new Error(r.stderr);return JSON.parse(r.stdout);}
function corners(crop){return [[crop.x,crop.y],[crop.x+crop.width-1,crop.y],[crop.x,crop.y+crop.height-1],[crop.x+crop.width-1,crop.y+crop.height-1]].map(([x,y])=>[x%256,y%256,x%2*255,255]);}
async function verifyOriginal(shown,source,label){await wallState(label+":before-clear-pins");await clearPins();await wallState(label+":after-clear-pins");const before=(await desktop("capture_history")).length;const copy=await capture(shown,"copy");result.lastCopy={label,shown,copy,history:await desktop("capture_history")};check((await desktop("capture_history")).length===before,`${label}: original copy adds no screenshot history`);const pinned=await capture(shown,"pin"),pin=pinned.pin.pin;const sample={label,shown,copy,pinned,pin};result.samples.push(sample);check(pin.content.kind==="reference"&&pin.content.libraryId===source.libraryId&&pin.content.imageId===source.imageId,`${label}: pin keeps exact library/image source`);check(isDeepStrictEqual(pin.crop,pinned.crop),`${label}: pin preserves original pixel crop`);check((await desktop("capture_history")).length===before,`${label}: reference pin adds no screenshot history`);await desktop("pin_clipboard");const entry=(await desktop("capture_history"))[0],clipboard=clipboardFile(entry);check(JSON.stringify(clipboard.size)===JSON.stringify([copy.crop.width,copy.crop.height]),`${label}: actual OS clipboard retains original crop dimensions`);check(JSON.stringify(clipboard.corners)===JSON.stringify(corners(copy.crop)),`${label}: actual OS clipboard retains original fine-detail corner bytes`);sample.clipboard=clipboard;await clearPins();}
function mainHwnd(){const r=spawnSync("powershell",["-NoProfile","-NonInteractive","-Command","Add-Type -AssemblyName UIAutomationClient; $owned=Get-CimInstance Win32_Process | Where-Object { $_.ExecutablePath -eq $env:KINSHOKO_E2E_EXECUTABLE } | Select-Object -First 1; if($owned){$condition=New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::ProcessIdProperty,[int]$owned.ProcessId); [System.Windows.Automation.AutomationElement]::RootElement.FindAll([System.Windows.Automation.TreeScope]::Children,$condition) | Where-Object { $_.Current.Name -eq 'Kinshoko' } | ForEach-Object { $_.Current.NativeWindowHandle }}"],{env:{...process.env,KINSHOKO_E2E_EXECUTABLE:application},encoding:"utf8",windowsHide:true});if(r.status!==0)throw new Error(r.stderr);return r.stdout.trim().split(/\s+/).filter(Boolean).map(Number);}
function observeNative(mode,point,placement){const r=spawnSync(process.env.KINSHOKO_PYTHON??"python",["e2e/native-wall-observe.py",application,resolve(manifestArg),mode,...(point?[String(point.x),String(point.y)]:[]),...(occluder?.pid?["--owned-occluder",String(occluder.pid)]:[]),...(placement?["--fixture-hwnd",String(placement.hwnd),"--fixture-script",placement.script,"--fixture-spawn-after-ms",String(placement.spawnRequestedAt),"--fixture-spawn-before-ms",String(placement.spawnReturnedAt)]:[])],{encoding:"utf8",windowsHide:true});if(r.status!==0)throw new Error(r.stderr);return JSON.parse(r.stdout);}
function nativeBounds(resize,focus=false){const script="Add-Type -AssemblyName UIAutomationClient; $owned=Get-CimInstance Win32_Process | Where-Object { $_.ExecutablePath -eq $env:KINSHOKO_E2E_EXECUTABLE } | Select-Object -First 1; $condition=New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::ProcessIdProperty,[int]$owned.ProcessId); $element=[System.Windows.Automation.AutomationElement]::RootElement.FindAll([System.Windows.Automation.TreeScope]::Children,$condition) | Where-Object { $_.Current.Name -eq 'Kinshoko' } | Select-Object -First 1; if(!$element){throw 'Owned main HWND absent'}; if($env:KINSHOKO_E2E_RESIZE_WIDTH){$transform=$element.GetCurrentPattern([System.Windows.Automation.TransformPattern]::Pattern); $transform.Resize([double]$env:KINSHOKO_E2E_RESIZE_WIDTH,[double]$env:KINSHOKO_E2E_RESIZE_HEIGHT)}; if($env:KINSHOKO_E2E_FOCUS){$element.SetFocus()}; $r=$element.Current.BoundingRectangle; @{x=$r.X;y=$r.Y;width=$r.Width;height=$r.Height;hwnd=$element.Current.NativeWindowHandle} | ConvertTo-Json -Compress";const r=spawnSync("powershell",["-NoProfile","-NonInteractive","-Command",script],{env:{...process.env,KINSHOKO_E2E_EXECUTABLE:application,...(focus?{KINSHOKO_E2E_FOCUS:"1"}:{}),...(resize?{KINSHOKO_E2E_RESIZE_WIDTH:String(resize.width),KINSHOKO_E2E_RESIZE_HEIGHT:String(resize.height)}:{})},encoding:"utf8",windowsHide:true});if(r.status!==0)throw new Error(r.stderr);return JSON.parse(r.stdout);}
function killOwn(){return spawnSync("powershell",["-NoProfile","-NonInteractive","-Command","Get-CimInstance Win32_Process | Where-Object { $_.ExecutablePath -eq $env:KINSHOKO_E2E_EXECUTABLE } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }"],{env:{...process.env,KINSHOKO_E2E_EXECUTABLE:application},encoding:"utf8",windowsHide:true});}
try{
 driver=spawn(process.env.KINSHOKO_TAURI_DRIVER??"C:/Users/yuk1no/.cargo/bin/tauri-driver.exe",["--port",String(port),"--native-port",String(port+1),"--native-driver",resolve(edgeArg)],{env:{...process.env,KINSHOKO_DATA_DIR:join(work,"app-data"),KINSHOKO_SKIP_AUTOSTART:"1",WEBVIEW2_USER_DATA_FOLDER:join(work,"webview")},stdio:["ignore","pipe","pipe"],windowsHide:true});
 driver.stdout.on("data",bytes=>observeNativeLog("stdout",bytes));driver.stderr.on("data",bytes=>observeNativeLog("stderr",bytes));
 await until("driver",()=>fetch(endpoint+"/status").then(r=>r.ok));await startSession();
 result.environment=await invoke("diagnostics_report",{purpose:"T17 original wall capture"});
 const first=await library("create_library",{parent:join(work,"libraries"),name:"原图来源 A"});await importFiles(first,[detail]);
 const firstCard=(await browse(first.id)).cards[0];result.first={info:first,card:firstCard};
 if(raceOnly){
  await library("set_safe_mode",{on:false});await library("edit",{libraryId:first.id,ids:[firstCard.imageId],edits:[{kind:"setRating",rating:"explicit"}]});await reload();await until("adult visible with global mode off",()=>exec("return document.querySelector('.card')?.dataset.veiled==='false'"));
  const seed=await begin(),mainOrigin=await native("inner_position");
  await desktop("finish_capture",{token:seed.token,region:{x:mainOrigin.x+20-seed.origin.x,y:mainOrigin.y+20-seed.origin.y,width:8,height:8},action:"copy"});
  result.clipboardSeed={clipboard:readClipboard("clipboard-seed"),metadata:clipboardMetadata(),history:await desktop("capture_history")};
  const shown=await bottomOriginal(firstCard.id),frozen=await begin(),selected=selection(shown,frozen);
  result.race={shown,selected,frozenPixels:await frozenPatch(frozen,shown,selected),startedAt:new Date().toISOString(),startedUnix:Date.now(),nativeLogOffset:nativeLog.events.length};
  await exec("window.__copyResult={pending:true}; window.__TAURI_INTERNALS__.invoke('plugin:desktop|finish_capture',arguments[0]).then(()=>window.__copyResult={ok:true,at:Date.now()},error=>window.__copyResult={error:String(error),at:Date.now()});",[{token:frozen.token,region:selected.region,action:"copy"}]);
  await delay(Number(process.env.KINSHOKO_RACE_DELAY??400));
  result.race.beforeRevocation=await exec("return window.__copyResult");
  check(result.race.beforeRevocation.pending===true,"slow decode is genuinely still running before mode revocation");
  result.race.modeRequestAt=new Date().toISOString();await library("set_safe_mode",{on:true});result.race.modeReturnedAt=new Date().toISOString();result.race.modeReturnedUnix=Date.now();result.race.afterModeCopy=await exec("return window.__copyResult");result.race.checkpointClipboard=readClipboard("clipboard-after-mode-return");result.race.checkpointMetadata=clipboardMetadata();
  result.race.copy=await until("slow original completion",()=>exec("return window.__copyResult&&!window.__copyResult.pending?window.__copyResult:null"),120000);
  result.race.completedAfterRevocation=result.race.copy.at>=result.race.modeReturnedUnix;result.race.finalClipboard=readClipboard("clipboard-after-copy-complete");
  result.race.finalMetadata=clipboardMetadata();result.race.finalHistory=await desktop("capture_history");
  const timing=nativeLog.events.slice(result.race.nativeLogOffset).filter(e=>e.at>=result.race.startedUnix);
  result.race.sourcePreparationBegin=timing.find(e=>e.line.startsWith("capture.source.prepare.begin "));
  result.race.sourcePreparationEnd=timing.find(e=>e.line.startsWith("capture.source.prepare.end "));
  result.race.formatPreparationBegin=timing.find(e=>e.line.startsWith("clipboard.prepare.begin "));
  result.race.formatPreparationEnd=timing.find(e=>e.line.startsWith("clipboard.prepare.end "));
  result.race.modeReturnedDuringSourcePreparation=result.race.sourcePreparationBegin?.at<result.race.modeReturnedUnix&&result.race.modeReturnedUnix<result.race.sourcePreparationEnd?.at;
  result.race.sameSeedPng=sha(result.clipboardSeed.clipboard.artifact)===sha(result.race.checkpointClipboard.artifact)&&sha(result.race.checkpointClipboard.artifact)===sha(result.race.finalClipboard.artifact);
  result.race.sameClipboardSequence=[result.clipboardSeed.metadata,result.race.checkpointMetadata,result.race.finalMetadata].every(m=>m.stableSequence&&m.formats>0&&m.formatsLastError===0&&m.sequence===result.clipboardSeed.metadata.sequence);
  result.race.sameHistory=isDeepStrictEqual(result.clipboardSeed.history,result.race.finalHistory);
  check(result.race.modeReturnedDuringSourcePreparation,"actual mode commit returns while the real source decode/crop preparation is still running");
  check(result.race.sameSeedPng&&result.race.sameClipboardSequence&&result.race.sameHistory,"mode revocation preserves actual seed PNG bytes, stable OS sequence and screenshot history");
  await desktop("pin_clipboard");const entry=(await desktop("capture_history"))[0];result.race.clipboard=clipboardFile(entry);
  result.race.containsOriginal=JSON.stringify(result.race.clipboard.size)===JSON.stringify([selected.crop.width,selected.crop.height])&&JSON.stringify(result.race.clipboard.corners)===JSON.stringify(corners(selected.crop));
  result.race.provedLateWrite=result.race.containsOriginal&&isDeepStrictEqual(result.race.checkpointClipboard.size,[8,8])&&result.race.finalClipboard.observedAtUnix>result.race.checkpointClipboard.observedAtUnix;
  check(isDeepStrictEqual(result.race.checkpointClipboard.size,[8,8]),"actual OS clipboard after mode return still contains the owned seed before slow-copy completion");
  check(!result.race.copy.ok&&!result.race.containsOriginal,"safe-mode revocation during slow original decode cannot commit late original pixels to the real OS clipboard");
  check(result.race.copy.error?.includes("安全模式已变化")&&isDeepStrictEqual(result.race.finalClipboard.size,[8,8]),"the committed mode generation revokes the actual late write and preserves the seed");
 }else{
  const second=await library("create_library",{parent:join(work,"libraries"),name:"当前独立库 B"});await importFiles(second,[detail]);await reload();
  let shown=await bottomOriginal(firstCard.id);check(shown.thumbWidth<originalWidth,"formal waterfall displays a reduced derivative of the high-resolution original");result.dpr=shown.dpr;
  if(process.env.KINSHOKO_CAPTURE_DPR)check(Math.abs(shown.dpr-Number(process.env.KINSHOKO_CAPTURE_DPR))<.001,"requested WebView DPR is actual; this is not system DPI acceptance");
  let aggregate=(await library("workspace_browse",{query:{scope:{kind:"all"},conditions:{conditions:[]},cursor:null,limit:500,thumbnailPx:256},safeMode:true})).cards.find(c=>c.id===firstCard.id);
  check(aggregate.sources.length===2,"real identical originals aggregate with two independent registered sources");
  await verifyOriginal(shown,aggregate,"initial aggregate waterfall");await screenshot("wall-original-reference.png");
  const prior=await begin();await desktop("cancel_capture",{token:prior.token});const fresh=await begin();
  await desktop("cancel_capture",{token:prior.token});check((await desktop("frozen_screen"))?.image===fresh.frozen.image,"late old cancel does not close the next native capture");
  const selected=selection(shown,fresh);const rejected=await desktop("finish_capture",{token:prior.token,region:selected.region,action:"copy"}).then(()=>false,()=>true);check(rejected&&(await desktop("frozen_screen"))?.image===fresh.frozen.image,"late old finish cannot consume a new native capture");await desktop("cancel_capture",{token:fresh.token});
  result.staleInput=await staleInput();await exec("window.__lateReport=arguments[0]",[result.staleInput]);
  await verifyOriginal(await bottomOriginal(firstCard.id),aggregate,"late prior source report");
  // Add unique content to force actual virtualization, then scroll out and back before F1.
  const extra=Array.from({length:120},(_,i)=>{const path=join(work,"sources",`other-${i}.png`);png(path,80+(i%3)*20,100+(i%4)*30,i+1);return path;});await importFiles(second,extra);await reload();
  await until("updated 121-card production wall",()=>exec("return document.querySelector('.wall')?.dataset.total==='121'&&document.querySelector('.card img')?.complete"));
  await exec("const w=document.querySelector('.wall');w.scrollTop=0;w.dispatchEvent(new Event('scroll',{bubbles:true}));");
  await until("top population before virtual scroll",()=>exec("return document.querySelector('.wall').scrollTop<1&&document.querySelectorAll('.card').length>0&&![...document.querySelectorAll('.card')].some(n=>n.dataset.id===arguments[0])",[firstCard.id]));
  const initialIds=await exec("return [...document.querySelectorAll('.card')].map(n=>n.dataset.id)");result.virtualScroll={initialIds};
  await exec("const el=document.querySelector('.wall');el.scrollTop=el.scrollHeight;el.dispatchEvent(new Event('scroll',{bubbles:true}));");
  await until("recycled bottom population",()=>exec("return [...document.querySelectorAll('.card')].some(n=>!arguments[0].includes(n.dataset.id))",[initialIds]));
  result.virtualScroll.bottomIds=await exec("return [...document.querySelectorAll('.card')].map(n=>n.dataset.id)");check(result.virtualScroll.bottomIds.some(id=>!initialIds.includes(id)),"actual virtualized wall recycles visible card population");
  await bottomOriginal(firstCard.id);
  await exec("const el=document.querySelector('.wall');el.scrollTop=0;el.dispatchEvent(new Event('scroll',{bubbles:true}));");
  await until("original virtualized out",()=>exec("return ![...document.querySelectorAll('.card')].some(n=>n.dataset.id===arguments[0])",[firstCard.id]));
  await exec("const el=document.querySelector('.wall');el.scrollTop=el.scrollHeight;el.dispatchEvent(new Event('scroll',{bubbles:true}));");
  shown=await bottomOriginal(firstCard.id);await verifyOriginal(shown,aggregate,"immediate virtual return");
  const size=nativeBounds();result.resize={before:size,beforeInner:await native("inner_size")};result.resize.resized=nativeBounds({width:Math.max(850,size.width-220),height:size.height});result.resize.afterInner=await until("real native resized client width",async()=>{const n=await native("inner_size");return n.width!==result.resize.beforeInner.width?n:null;});check(result.resize.beforeInner.width!==result.resize.afterInner.width,"UIAutomation changes the real native main client width");
  await verifyOriginal(await bottomOriginal(firstCard.id),aggregate,"native width reflow");
  nativeBounds(size);await until("real native width restored",async()=>(await native("inner_size")).width===result.resize.beforeInner.width);await verifyOriginal(await bottomOriginal(firstCard.id),aggregate,"continuous resize return");
  const priorInstance=await exec("return window.__documentMarker");
  await reload();
  await exec("const el=document.querySelector('.wall');el.scrollTop=el.scrollHeight;el.dispatchEvent(new Event('scroll',{bubbles:true}));");
  await verifyOriginal(await bottomOriginal(firstCard.id),aggregate,"document re-creation");
  check((await exec("return window.__documentMarker"))!==priorInstance,"real WebView document is re-created before the next source handshake");
  // Destroy and re-create the real main HWND while a reference pin keeps the WebDriver browser alive.
  const oldReport=await staleInput();
  const oldHandle=await wd("GET",`${base}/window`),oldNative=mainHwnd();
  const beforeHandles=await wd("GET",`${base}/window/handles`);
  await capture(await bottomOriginal(firstCard.id),"pin");
  const survivor=await until("spare native WebView",async()=>(await wd("GET",`${base}/window/handles`)).find(h=>!beforeHandles.includes(h)));
  await wd("POST",`${base}/window`,{handle:survivor});const nativeClosed=observeNative("close");result.nativeClose=nativeClosed;await until("native main label actually gone",async()=>!(await windows()).includes("main"));
  const reopen=spawn(application,[],{env:{...process.env,KINSHOKO_DATA_DIR:join(work,"app-data"),KINSHOKO_SKIP_AUTOSTART:"1",WEBVIEW2_USER_DATA_FOLDER:join(work,"webview")},windowsHide:true,stdio:"ignore"});
  await new Promise((done,reject)=>{reopen.once("error",reject);reopen.once("exit",done);});
  const newHandle=await until("re-created native main window",async()=>{for(const handle of await wd("GET",`${base}/window/handles`)){if(handle===survivor)continue;try{await wd("POST",`${base}/window`,{handle});if(await exec("return window.__TAURI_INTERNALS__.metadata.currentWindow.label==='main'"))return handle;}catch{}}return null;});
  await wd("POST",`${base}/window`,{handle:newHandle});await until("re-created formal wall",()=>exec("return !!document.querySelector('.wall')"));await observeRequests();
  await exec("window.__lateReport=arguments[0];const el=document.querySelector('.wall');el.scrollTop=el.scrollHeight;el.dispatchEvent(new Event('scroll',{bubbles:true}));",[oldReport]);
  const newNative=mainHwnd();result.hwndRecreation={oldHandle,newHandle,oldNative,newNative,nativeClosed};
  check(oldNative.length===1&&newNative.length===1&&nativeClosed.destroyed===true,"real main HWND is destroyed and re-created");
  await verifyOriginal(await bottomOriginal(firstCard.id),aggregate,"native HWND re-creation with late old report");
  // Prove a visible reference pin uses its original before revoking that exact native view.
  await clearPins();
  const sourcePin = (await capture(await bottomOriginal(firstCard.id),"pin")).pin;
  const pinId = sourcePin.pin.id, pinLabel = `pin-${pinId}`;
  const pinFrame = await until("loaded reference pin for close proof",async()=>{
    const frame=await desktop("pin_frame",{pin:pinId});
    return frame&&!frame.veiled&&!frame.unavailable&&await native("is_visible",pinLabel)?frame:null;
  });
  const selectPin = frozen => {
    const selected=selection(pinFrame.content,frozen), shown=pinFrame.content, pin=pinFrame.pin;
    const ox=selected.region.x+frozen.origin.x-shown.x,oy=selected.region.y+frozen.origin.y-shown.y;
    selected.crop={x:(pin.crop?.x??0)+Math.floor(ox*pin.width/shown.width),y:(pin.crop?.y??0)+Math.floor(oy*pin.height/shown.height),width:Math.ceil((ox+selected.region.width)*pin.width/shown.width)-Math.floor(ox*pin.width/shown.width),height:Math.ceil((oy+selected.region.height)*pin.height/shown.height)-Math.floor(oy*pin.height/shown.height)};
    return selected;
  };
  const pinHistory=(await desktop("capture_history")).length,pinBaseline=await begin(),pinBaselineSelection=selectPin(pinBaseline);
  await desktop("finish_capture",{token:pinBaseline.token,region:pinBaselineSelection.region,action:"copy"});
  const pinBaselineClipboard=readClipboard("closed-pin-baseline");
  check((await desktop("capture_history")).length===pinHistory&&isDeepStrictEqual(pinBaselineClipboard.size,[pinBaselineSelection.crop.width,pinBaselineSelection.crop.height])&&isDeepStrictEqual(pinBaselineClipboard.corners,corners(pinBaselineSelection.crop)),"visible pin baseline reads its exact original crop without screenshot history");
  const pinFrozen=await begin(),pinSelected=selectPin(pinFrozen);
  result.closedPin={pinId,pinLabel,frame:pinFrame,baseline:{selected:pinBaselineSelection,clipboard:pinBaselineClipboard},token:pinFrozen.token,selected:pinSelected,frozenPixels:await frozenPatch(pinFrozen,pinFrame.content,pinSelected),beforeClipboard:readClipboard("closed-pin-before")};
  const pinMainHandle=await wd("GET",`${base}/window`);
  let pinHandle;
  for(const handle of await wd("GET",`${base}/window/handles`)){
    if(handle===pinMainHandle)continue;
    await wd("POST",`${base}/window`,{handle});
    if(await exec("return window.__TAURI_INTERNALS__.metadata.currentWindow.label===arguments[0]",[pinLabel])){pinHandle=handle;break;}
  }
  check(!!pinHandle,"close command is sent from the exact owned reference pin WebView");
  result.closedPin.closeRequestedAt=new Date().toISOString();
  await exec("void window.__TAURI_INTERNALS__.invoke('plugin:desktop|close_pin',{pin:arguments[0]});return true",[pinId]);
  await wd("POST",`${base}/window`,{handle:pinMainHandle});
  await until("reference pin removed after public close",async()=>!(await windows()).includes(pinLabel)&&await desktop("pin_frame",{pin:pinId})===null);
  result.closedPin.removedObservedAt=new Date().toISOString();
  result.closedPin.finish=await desktop("finish_capture",{token:pinFrozen.token,region:pinSelected.region,action:"copy"}).then(()=>({ok:true}),error=>({error:String(error)}));
  result.closedPin.afterClipboard=readClipboard("closed-pin-after");
  check(!result.closedPin.finish.ok&&(await desktop("capture_history")).length===pinHistory,"a removed frozen reference pin rejects original copy without a screenshot fallback");
  check(sha(result.closedPin.beforeClipboard.artifact)===sha(result.closedPin.afterClipboard.artifact),"removed pin rejection preserves the actual OS clipboard image");
  // Cross-card/toolbar regions stay ordinary screen captures.
  const ordinaryBefore=(await desktop("capture_history")).length, outside=await begin();await desktop("finish_capture",{token:outside.token,region:{x:(await native("inner_position")).x+30-outside.origin.x,y:(await native("inner_position")).y+30-outside.origin.y,width:80,height:60},action:"copy"});const ordinary=(await desktop("capture_history"))[0];check((await desktop("capture_history")).length===ordinaryBefore+1&&ordinary.width===80&&ordinary.height===60,"outside a single reference remains a native screen capture");
  const crossCards=await exec("const w=document.querySelector('.wall').getBoundingClientRect();return [...document.querySelectorAll('.card img')].filter(i=>i.complete&&i.naturalWidth).map(i=>{const b=i.getBoundingClientRect(),left=Math.max(b.left,w.left),right=Math.min(b.right,w.right),top=Math.max(b.top,w.top),bottom=Math.min(b.bottom,w.bottom);return {id:i.closest('.card').dataset.id,x:(left+right)/2,y:(top+bottom)/2,visible:right-left>8&&bottom-top>8};}).filter(b=>b.visible).slice(0,2)");
  check(crossCards.length===2,"two different loaded cards are actually visible for the cross-card selection");
  const crossBefore=(await desktop("capture_history")).length,cross=await begin(),crossOrigin=await native("inner_position"),crossDpr=await exec("return devicePixelRatio");
  const crossRegion={x:crossOrigin.x+Math.floor(Math.min(...crossCards.map(b=>b.x))*crossDpr)-cross.origin.x,y:crossOrigin.y+Math.floor(Math.min(...crossCards.map(b=>b.y))*crossDpr)-cross.origin.y,width:Math.max(4,Math.ceil(Math.abs(crossCards[0].x-crossCards[1].x)*crossDpr)+4),height:Math.max(4,Math.ceil(Math.abs(crossCards[0].y-crossCards[1].y)*crossDpr)+4)};
  await desktop("finish_capture",{token:cross.token,region:crossRegion,action:"copy"});const crossEntry=(await desktop("capture_history"))[0];result.crossCard={cards:crossCards,region:crossRegion,entry:crossEntry,clipboard:readClipboard("cross-card-clipboard")};
  check((await desktop("capture_history")).length===crossBefore+1&&crossEntry.width===crossRegion.width&&crossEntry.height===crossRegion.height&&isDeepStrictEqual(result.crossCard.clipboard.size,[crossRegion.width,crossRegion.height]),"cross-card selection uses native screen pixels and adds ordinary screenshot history");
  // A genuine topmost external native window occludes the source.
  shown=await bottomOriginal(firstCard.id);const covering={x:shown.x+Math.floor(shown.width/4)-8,y:shown.y+Math.floor(shown.height/4)-8,width:Math.floor(shown.width/8)+30,height:Math.floor(shown.height/8)+30};
  const formScript=join(work,"occluder.ps1");writeFileSync(formScript,`$ErrorActionPreference='Stop'\nAdd-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public static class T17FixtureNative { [DllImport("user32.dll",SetLastError=true)] public static extern IntPtr SetThreadDpiAwarenessContext(IntPtr value); [DllImport("user32.dll",SetLastError=true)] public static extern bool SetWindowPos(IntPtr hwnd,IntPtr after,int x,int y,int width,int height,uint flags); [DllImport("user32.dll",EntryPoint="GetWindowLongPtrW",SetLastError=true)] public static extern IntPtr GetWindowLongPtr(IntPtr hwnd,int index); }'\n$dpiContext=[T17FixtureNative]::SetThreadDpiAwarenessContext([IntPtr]::new(-4))\nAdd-Type -AssemblyName System.Windows.Forms\nAdd-Type -AssemblyName System.Drawing\n$f=New-Object System.Windows.Forms.Form\n$f.AutoScaleMode='None'\n$f.FormBorderStyle='None'\n$f.StartPosition='Manual'\n$f.Location=New-Object System.Drawing.Point(${covering.x},${covering.y})\n$f.ClientSize=New-Object System.Drawing.Size(${covering.width},${covering.height})\n$f.TopMost=$true\n$f.BackColor=[System.Drawing.Color]::FromArgb(3,17,229)\n$f.Add_Shown({[void]$f.BeginInvoke([Action]{$placed=[T17FixtureNative]::SetWindowPos($f.Handle,[IntPtr]::new(-1),${covering.x},${covering.y},${covering.width},${covering.height},0x50);if(!$placed){throw 'Owned fixture placement failed'};$ready=@{pid=$PID;hwnd=$f.Handle.ToInt64();placed=$placed;previousDpiContext=$dpiContext.ToInt64();immediateExtendedStyle=[T17FixtureNative]::GetWindowLongPtr($f.Handle,-20).ToInt64()};[IO.File]::WriteAllText('${join(work,"occluder-ready.json").replaceAll("'","''")}',($ready|ConvertTo-Json -Compress))})})\n[System.Windows.Forms.Application]::Run($f)\n`);
  const fixtureSpawnRequestedAt=Date.now();occluder=spawn("powershell",["-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-STA","-File",formScript],{windowsHide:true,stdio:["ignore","pipe","pipe"]});result.occluder={pid:occluder.pid,requested:covering,script:formScript,spawnRequestedAt:fixtureSpawnRequestedAt,spawnReturnedAt:Date.now()};occluder.stdout.on("data",bytes=>appendFileSync(join(work,"occluder-stdout.txt"),bytes));occluder.stderr.on("data",bytes=>appendFileSync(join(work,"occluder-stderr.txt"),bytes));occluder.on("exit",(code,signal)=>{result.occluder.exit={code,signal,at:new Date().toISOString()};});
  result.occluder.ready=await until("owned external fixture ready",()=>{try{return JSON.parse(readFileSync(join(work,"occluder-ready.json"),"utf8").replace(/^\uFEFF/,""));}catch{return false;}});
  check(result.occluder.ready.pid===occluder.pid&&result.occluder.ready.placed,"fixture HWND is tied to the exact spawned child PID");
  result.occluder.beforeMainFocus=observeNative("observe",{x:covering.x+10,y:covering.y+10});
  result.occluder.beforeCapture=observeNative("focus-fixture",{x:covering.x+10,y:covering.y+10},{hwnd:result.occluder.ready.hwnd,script:formScript,spawnRequestedAt:result.occluder.spawnRequestedAt,spawnReturnedAt:result.occluder.spawnReturnedAt});
  check(result.occluder.beforeCapture.foregroundHwnd===result.occluder.beforeCapture.mainHwnd&&result.occluder.beforeCapture.foregroundPid===result.occluder.beforeCapture.pid,"real main foreground is confirmed while external fixture stays over its selected pixels");
  const actualOccluder=result.occluder.beforeCapture.testOccluderWindows.find(w=>w.hwnd===result.occluder.ready.hwnd);
  check(actualOccluder?.visible&&!actualOccluder.iconic&&actualOccluder.extendedStyle.topmost&&["x","y","width","height"].every(k=>actualOccluder.rect[k]===covering[k])&&result.occluder.beforeCapture.rawVisibleZOrder.find(w=>w.hwnd===actualOccluder.hwnd)?.index<result.occluder.beforeCapture.mainZIndex&&result.occluder.beforeCapture.pointWindow?.rootHwnd===actualOccluder.hwnd&&result.occluder.beforeCapture.pointWindow?.rootPid===occluder.pid,"actual owned external HWND is topmost above the main window with exact physical bounds and the OS point hit identifies that visible fixture");
  const coveredBefore=(await desktop("capture_history")).length;const coveredCopy=await capture(shown,"copy",false);check((await desktop("capture_history")).length===coveredBefore+1,"external topmost HWND prevents original-source capture under its coverage");const coveredEntry=(await desktop("capture_history"))[0];check(coveredEntry.width===coveredCopy.region.width&&coveredEntry.height===coveredCopy.region.height,"native occluded selection preserves screen rather than original dimensions");result.occluder.clipboard=readClipboard("external-occlusion-clipboard");check(result.occluder.clipboard.corners.every(pixel=>isDeepStrictEqual(pixel,[3,17,229,255])),"actual OS clipboard contains the owned external window's blue pixels");occluder.kill();occluder=null;
  await clearPins();shown=await bottomOriginal(firstCard.id);const invalidBefore=(await desktop("capture_history")).length,invalid=await begin(),invalidSelected=selection(shown,invalid);
  result.knownInvalid={source:{libraryId:aggregate.libraryId,imageId:aggregate.imageId,contentId:aggregate.id},frozenPixels:await frozenPatch(invalid,shown,invalidSelected),clipboardBefore:readClipboard("known-invalid-before")};
  await library("unregister_library",{libraryId:result.knownInvalid.source.libraryId});
  result.knownInvalid.finish=await desktop("finish_capture",{token:invalid.token,region:invalidSelected.region,action:"copy"}).then(()=>({ok:true}),error=>({error:String(error)}));result.knownInvalid.clipboardAfter=readClipboard("known-invalid-after");
  check(!result.knownInvalid.finish.ok&&(await desktop("capture_history")).length===invalidBefore,"an unregistered known frozen source rejects capture without a screen-frame history fallback");
  check(sha(result.knownInvalid.clipboardBefore.artifact)===sha(result.knownInvalid.clipboardAfter.artifact),"known invalid source rejection preserves the actual OS clipboard bytes");
  check(sha(detail)===sourceHash,"original high-resolution file bytes remain unchanged");
  result.requests=await exec("return window.__captureRequests");result.lateSent=await exec("return window.__lateSent");await screenshot("wall-after-reflow-and-capture.png");
 }
 result.status="passed";
}catch(error){result.status="failed";result.error=error.stack??String(error);if(base){await screenshot("failure.png").catch(()=>{});await exec("return document.documentElement.outerHTML").then(html=>writeFileSync(join(work,"failure.html"),html)).catch(()=>{});await wallState("failure").catch(()=>{});try{result.failureNative=observeNative("observe");}catch(nativeError){result.failureNative={error:String(nativeError)};}result.requests=await exec("return window.__captureRequests").catch(()=>undefined);result.lateSent=await exec("return window.__lateSent").catch(()=>undefined);}console.error(error);process.exitCode=1;
}finally{
 result.nativeClipboardDiagnostics=nativeLog.events;result.settingsAfter=recordSettings("after");result.finishedAt=new Date().toISOString();writeFileSync(join(work,"result.json"),JSON.stringify(result,null,2));if(occluder)occluder.kill();if(base)await wd("DELETE",base).catch(()=>{});killOwn();if(driver?.pid)spawnSync("taskkill",["/PID",String(driver.pid),"/T","/F"],{stdio:"ignore",windowsHide:true});console.log(`Evidence: ${work}`);
}
